LIB_ALGOS:= \
    AES_C \
    ARCFOUR_C \
    BASE64 \
    BIGINT_C \
    BLAKE_C \
    BMW_C \
    CAST5 \
    CAST6 \
    CSCIPHER_SMALL_C \
    CUBEHASH_C \
    DES \
    DSA \
    ECHO_C \
    GRAIN \
    GROESTL_C \
    JH_SIMPLE_SMALL_C \
    KECCAK_C \
    KHAZAD_SMALL_C \
    MD5_C \
    MICKEY128 \
    NOEKEON_C \
    PRESENT \
    PRF_TLS12 \
    RABBIT_C \
    RC5 \
    RC6 \
    RSAES_OAEP \
    RSAES_PKCS1V15 \
    SALSA20_C \
    SEED_C \
    SERPENT_BITSLICE \
    SHA1_C \
    SHA2_C \
    SHABAL_C \
    SKEIN_C \
    TDES \
    TRIVIUM \
    XTEA_C \
    HFAL_HMAC \
    BCAL_BASIC \
    SCAL_BASIC \
    HFAL_ALGOS \
    BCAL_ALGOS \
    SCAL_ALGOS


