#define LED_READY PB7
#define LED_CALIBRATING PC6
#define LED_USBON PF4
#define LED_RUNNING PF5


#define LED_READY_ON {PORTB |= _BV(LED_READY);}
#define LED_READY_OFF {PORTB &= ~ _BV(LED_READY);}
#define CONFIGURE_LED_READY DDRD |= _BV(LED_READY);

#define LED_CALIBRATING_ON {PORTC |= _BV(LED_CALIBRATING);}
#define LED_CALIBRATING_OFF {PORTC &= ~ _BV(LED_CALIBRATING);}
#define CONFIGURE_LED_CALIBRATING DDRC |= _BV(LED_CALIBRATING);

#define LED_USBON_ON {PORTF |= _BV(LED_USBON);}
#define LED_USBON_OFF {PORTF &= ~ _BV(LED_USBON);}
#define CONFIGURE_LED_USBON DDRF |= _BV(LED_USBON);

#define LED_RUNNING_ON {PORTF |= _BV(LED_RUNNING);}
#define LED_RUNNING_OFF {PORTF &= ~ _BV(LED_RUNNING);}
#define CONFIGURE_LED_RUNNING DDRF |= _BV(LED_RUNNING);

#define LASER_SUPPLY_EN PF0
#define LASER_SUPPLY_ON  {PORTF |= _BV(LASER_SUPPLY_EN);}
#define LASER_SUPPLY_OFF {PORTF &= ~_BV(LASER_SUPPLY_EN);}

#define KEY_ON PD0
#define KEY_START PD1

#define CONFIGURE_KEY_ON PORTD|=_BV(PD0);
#define CONFIGURE_KEY_START PORTD|=_BV(PD1);

#define KEY_ON_PIN (PIND & _BV(KEY_ON))
#define KEY_START_PIN (PIND & _BV(KEY_START))

#define SUPPLY_SENSE PD3
#define SUPPLY_SENSE_PIN (PIND & _BV(PD3))

#define IH1 PB5
#define IL1 PF7
#define IH2 PB6
#define IL2 PD5

#define HSYNC PD2

#define ENABLE_INT3 EIMSK |=_BV(INT3);
#define DISABLE_INT3 EIMSK &=~BV(INT3);
#define CONFIGURE_INT3 EICRA|=_BV(ISC30);	//any edge

#define ENABLE_INT2 EIMSK |=_BV(INT2);
#define DISABLE_INT2 EIMSK &=~BV(INT2);
#define CONFIGURE_INT2 EICRA|=_BV(ISC21);	//falling edge
 
#define ENABLE_INT0 EIMSK |=_BV(INT0);
#define DISABLE_INT0 EIMSK &=~BV(INT0);
#define CONFIGURE_INT0 EICRA|=_BV(ISC01);	//falling edge

#define ENABLE_INT1 EIMSK |=_BV(INT1);
#define DISABLE_INT1 EIMSK &=~BV(INT1);
#define CONFIGURE_INT1 EICRA|=_BV(ISC11);	//falling edge
 
#define ENABLE_INT6 EIMSK |=_BV(INT6);
#define DISABLE_INT6 EIMSK &=~BV(INT6);
#define CONFIGURE_INT6 EICRB|=_BV(ISC61);		//falling edge
 
#define POWER_DOWN {SMCR |= _BV(SM1)|_BV(SE);SLEEP;}
#define POWER_REDUCE {PRR0 = _BV(PRTWI)|_BV(PRADC); PRR1 = _BV(PRUSART1);}

#define ROT1_PIN (EIFR & _BV(INTF6))
#define CLEAR_ROT1_PIN {EIFR &= ~_BV(INTF6);}
