// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JetonAdmin {
    
    
    public partial class MainWindow {
        
        private Gtk.UIManager UIManager;
        
        private Gtk.Action DateiAction;
        
        private Gtk.Action BeendenAction;
        
        private Gtk.Action VerbindenAction;
        
        private Gtk.Action TrennenAction;
        
        private Gtk.VBox vbox1;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.Notebook notebook1;
        
        private JetonAdmin.UserScreen userscreen1;
        
        private Gtk.Label label1;
        
        private Gtk.Label label5;
        
        private Gtk.Label label8;
        
        private Gtk.Statusbar statusbar1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget JetonAdmin.MainWindow
            this.UIManager = new Gtk.UIManager();
            Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
            this.DateiAction = new Gtk.Action("DateiAction", Mono.Unix.Catalog.GetString("_Datei"), null, null);
            this.DateiAction.ShortLabel = Mono.Unix.Catalog.GetString("_Datei");
            w1.Add(this.DateiAction, null);
            this.BeendenAction = new Gtk.Action("BeendenAction", Mono.Unix.Catalog.GetString("_Beenden"), null, "gtk-quit");
            this.BeendenAction.ShortLabel = Mono.Unix.Catalog.GetString("_Beenden");
            w1.Add(this.BeendenAction, null);
            this.VerbindenAction = new Gtk.Action("VerbindenAction", Mono.Unix.Catalog.GetString("_Verbinden..."), null, "gtk-connect");
            this.VerbindenAction.ShortLabel = Mono.Unix.Catalog.GetString("_Verbinden...");
            w1.Add(this.VerbindenAction, null);
            this.TrennenAction = new Gtk.Action("TrennenAction", Mono.Unix.Catalog.GetString("_Trennen"), null, "gtk-disconnect");
            this.TrennenAction.ShortLabel = Mono.Unix.Catalog.GetString("_Trennen");
            w1.Add(this.TrennenAction, null);
            this.UIManager.InsertActionGroup(w1, 0);
            this.AddAccelGroup(this.UIManager.AccelGroup);
            this.Name = "JetonAdmin.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("Jeton Admin");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "stock_unknown", Gtk.IconSize.Menu, 16);
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child JetonAdmin.MainWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='DateiAction' action='DateiAction'><menuitem name='VerbindenAction' action='VerbindenAction'/><menuitem name='TrennenAction' action='TrennenAction'/><separator/><menuitem name='BeendenAction' action='BeendenAction'/></menu></menubar></ui>");
            this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox1.Add(this.menubar1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 1;
            this.notebook1.EnablePopup = true;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.userscreen1 = null;
            this.notebook1.Add(this.userscreen1);
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Benutzer");
            this.notebook1.SetTabLabel(this.userscreen1, this.label1);
            this.label1.ShowAll();
            // Notebook tab
            Gtk.Label w4 = new Gtk.Label();
            w4.Visible = true;
            this.notebook1.Add(w4);
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Artikel Bestand");
            this.notebook1.SetTabLabel(w4, this.label5);
            this.label5.ShowAll();
            // Notebook tab
            Gtk.Label w5 = new Gtk.Label();
            w5.Visible = true;
            this.notebook1.Add(w5);
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Transaktionen");
            this.notebook1.SetTabLabel(w5, this.label8);
            this.label8.ShowAll();
            this.vbox1.Add(this.notebook1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
            w6.Position = 1;
            // Container child vbox1.Gtk.Box+BoxChild
            this.statusbar1 = new Gtk.Statusbar();
            this.statusbar1.Name = "statusbar1";
            this.statusbar1.Spacing = 6;
            this.vbox1.Add(this.statusbar1);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
            w7.Position = 2;
            w7.Expand = false;
            w7.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 619;
            this.DefaultHeight = 587;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        }
    }
}
