// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JetonAdmin {
    
    
    public partial class MainWindow {
        
        private Gtk.Action DateiAction;
        
        private Gtk.Action BeendenAction;
        
        private Gtk.Action VerbindenAction;
        
        private Gtk.Action TrennenAction;
        
        private Gtk.VBox vbox1;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.Notebook notebook1;
        
        private Gtk.HPaned hpaned1;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Label label2;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.NodeView nodeview2;
        
        private Gtk.HButtonBox hbuttonbox1;
        
        private Gtk.Button button1;
        
        private Gtk.Button button2;
        
        private Gtk.VBox vbox6;
        
        private Gtk.Label label12;
        
        private Gtk.Table table1;
        
        private Gtk.Entry cardCreditEntry;
        
        private Gtk.Entry cardIdEntry;
        
        private Gtk.Entry cardNameEntry;
        
        private Gtk.Entry cardTreuhandEntry;
        
        private Gtk.ScrolledWindow GtkScrolledWindow1;
        
        private Gtk.NodeView nodeview3;
        
        private Gtk.Label label10;
        
        private Gtk.Label label11;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label label6;
        
        private Gtk.Label label9;
        
        private Gtk.VBox vbox3;
        
        private Gtk.CheckButton cardRoleLaborant;
        
        private Gtk.CheckButton cardRoleDoor;
        
        private Gtk.CheckButton cardRoleCreator;
        
        private Gtk.CheckButton cardRoleGod;
        
        private Gtk.HButtonBox hbuttonbox2;
        
        private Gtk.Button cardSaveBtn;
        
        private Gtk.Label label1;
        
        private Gtk.Label label5;
        
        private Gtk.Label label8;
        
        private Gtk.Statusbar statusbar1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget JetonAdmin.MainWindow
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.DateiAction = new Gtk.Action("DateiAction", Mono.Unix.Catalog.GetString("_Datei"), null, null);
            this.DateiAction.ShortLabel = Mono.Unix.Catalog.GetString("_Datei");
            w2.Add(this.DateiAction, null);
            this.BeendenAction = new Gtk.Action("BeendenAction", Mono.Unix.Catalog.GetString("_Beenden"), null, "gtk-quit");
            this.BeendenAction.ShortLabel = Mono.Unix.Catalog.GetString("_Beenden");
            w2.Add(this.BeendenAction, null);
            this.VerbindenAction = new Gtk.Action("VerbindenAction", Mono.Unix.Catalog.GetString("_Verbinden..."), null, "gtk-connect");
            this.VerbindenAction.ShortLabel = Mono.Unix.Catalog.GetString("_Verbinden...");
            w2.Add(this.VerbindenAction, null);
            this.TrennenAction = new Gtk.Action("TrennenAction", Mono.Unix.Catalog.GetString("_Trennen"), null, "gtk-disconnect");
            this.TrennenAction.ShortLabel = Mono.Unix.Catalog.GetString("_Trennen");
            w2.Add(this.TrennenAction, null);
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "JetonAdmin.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("MainWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child JetonAdmin.MainWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='DateiAction'><menuitem action='VerbindenAction'/><menuitem action='TrennenAction'/><separator/><menuitem action='BeendenAction'/></menu></menubar></ui>");
            this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox1.Add(this.menubar1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 0;
            this.notebook1.EnablePopup = true;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.hpaned1 = new Gtk.HPaned();
            this.hpaned1.CanFocus = true;
            this.hpaned1.Name = "hpaned1";
            this.hpaned1.Position = 221;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Ausgegebene Karten:");
            this.vbox2.Add(this.label2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.label2]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.nodeview2 = new Gtk.NodeView();
            this.nodeview2.CanFocus = true;
            this.nodeview2.Name = "nodeview2";
            this.nodeview2.HeadersClickable = true;
            this.GtkScrolledWindow.Add(this.nodeview2);
            this.vbox2.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
            w6.Position = 1;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbuttonbox1 = new Gtk.HButtonBox();
            this.hbuttonbox1.Name = "hbuttonbox1";
            this.hbuttonbox1.Homogeneous = true;
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.button1 = new Gtk.Button();
            this.button1.CanFocus = true;
            this.button1.Name = "button1";
            this.button1.UseStock = true;
            this.button1.UseUnderline = true;
            this.button1.Label = "gtk-add";
            this.hbuttonbox1.Add(this.button1);
            Gtk.ButtonBox.ButtonBoxChild w7 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.button1]));
            w7.Expand = false;
            w7.Fill = false;
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.button2 = new Gtk.Button();
            this.button2.CanFocus = true;
            this.button2.Name = "button2";
            this.button2.UseStock = true;
            this.button2.UseUnderline = true;
            this.button2.Label = "gtk-remove";
            this.hbuttonbox1.Add(this.button2);
            Gtk.ButtonBox.ButtonBoxChild w8 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.button2]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            this.vbox2.Add(this.hbuttonbox1);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox1]));
            w9.Position = 2;
            w9.Expand = false;
            w9.Fill = false;
            w9.Padding = ((uint)(5));
            this.hpaned1.Add(this.vbox2);
            Gtk.Paned.PanedChild w10 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.vbox2]));
            w10.Resize = false;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.vbox6 = new Gtk.VBox();
            this.vbox6.Name = "vbox6";
            this.vbox6.Spacing = 6;
            // Container child vbox6.Gtk.Box+BoxChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.LabelProp = Mono.Unix.Catalog.GetString("Details zur gewählten Karte:");
            this.vbox6.Add(this.label12);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox6[this.label12]));
            w11.Position = 0;
            w11.Expand = false;
            w11.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(6)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            this.table1.BorderWidth = ((uint)(9));
            // Container child table1.Gtk.Table+TableChild
            this.cardCreditEntry = new Gtk.Entry();
            this.cardCreditEntry.CanFocus = true;
            this.cardCreditEntry.Name = "cardCreditEntry";
            this.cardCreditEntry.IsEditable = true;
            this.cardCreditEntry.InvisibleChar = '●';
            this.table1.Add(this.cardCreditEntry);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.cardCreditEntry]));
            w12.TopAttach = ((uint)(3));
            w12.BottomAttach = ((uint)(4));
            w12.LeftAttach = ((uint)(1));
            w12.RightAttach = ((uint)(2));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.cardIdEntry = new Gtk.Entry();
            this.cardIdEntry.CanFocus = true;
            this.cardIdEntry.Name = "cardIdEntry";
            this.cardIdEntry.IsEditable = false;
            this.cardIdEntry.InvisibleChar = '●';
            this.table1.Add(this.cardIdEntry);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.cardIdEntry]));
            w13.LeftAttach = ((uint)(1));
            w13.RightAttach = ((uint)(2));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.cardNameEntry = new Gtk.Entry();
            this.cardNameEntry.CanFocus = true;
            this.cardNameEntry.Name = "cardNameEntry";
            this.cardNameEntry.IsEditable = true;
            this.cardNameEntry.InvisibleChar = '●';
            this.table1.Add(this.cardNameEntry);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.cardNameEntry]));
            w14.TopAttach = ((uint)(1));
            w14.BottomAttach = ((uint)(2));
            w14.LeftAttach = ((uint)(1));
            w14.RightAttach = ((uint)(2));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.cardTreuhandEntry = new Gtk.Entry();
            this.cardTreuhandEntry.CanFocus = true;
            this.cardTreuhandEntry.Name = "cardTreuhandEntry";
            this.cardTreuhandEntry.IsEditable = true;
            this.cardTreuhandEntry.InvisibleChar = '●';
            this.table1.Add(this.cardTreuhandEntry);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table1[this.cardTreuhandEntry]));
            w15.TopAttach = ((uint)(4));
            w15.BottomAttach = ((uint)(5));
            w15.LeftAttach = ((uint)(1));
            w15.RightAttach = ((uint)(2));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
            this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
            this.nodeview3 = new Gtk.NodeView();
            this.nodeview3.CanFocus = true;
            this.nodeview3.Name = "nodeview3";
            this.nodeview3.HeadersClickable = true;
            this.GtkScrolledWindow1.Add(this.nodeview3);
            this.table1.Add(this.GtkScrolledWindow1);
            Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindow1]));
            w17.TopAttach = ((uint)(5));
            w17.BottomAttach = ((uint)(6));
            w17.LeftAttach = ((uint)(1));
            w17.RightAttach = ((uint)(2));
            // Container child table1.Gtk.Table+TableChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("Treuhand-Konto:");
            this.table1.Add(this.label10);
            Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table1[this.label10]));
            w18.TopAttach = ((uint)(4));
            w18.BottomAttach = ((uint)(5));
            w18.XOptions = ((Gtk.AttachOptions)(4));
            w18.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("Transaktionen:");
            this.table1.Add(this.label11);
            Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table1[this.label11]));
            w19.TopAttach = ((uint)(5));
            w19.BottomAttach = ((uint)(6));
            w19.XOptions = ((Gtk.AttachOptions)(4));
            w19.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Karten ID:");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w20.XOptions = ((Gtk.AttachOptions)(4));
            w20.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Screen Name:");
            this.table1.Add(this.label4);
            Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
            w21.TopAttach = ((uint)(1));
            w21.BottomAttach = ((uint)(2));
            w21.XOptions = ((Gtk.AttachOptions)(4));
            w21.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Rollen:");
            this.table1.Add(this.label6);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table1[this.label6]));
            w22.TopAttach = ((uint)(2));
            w22.BottomAttach = ((uint)(3));
            w22.XOptions = ((Gtk.AttachOptions)(4));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("Guthaben:");
            this.table1.Add(this.label9);
            Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(this.table1[this.label9]));
            w23.TopAttach = ((uint)(3));
            w23.BottomAttach = ((uint)(4));
            w23.XOptions = ((Gtk.AttachOptions)(4));
            w23.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.cardRoleLaborant = new Gtk.CheckButton();
            this.cardRoleLaborant.CanFocus = true;
            this.cardRoleLaborant.Name = "cardRoleLaborant";
            this.cardRoleLaborant.Label = Mono.Unix.Catalog.GetString("Laborant");
            this.cardRoleLaborant.DrawIndicator = true;
            this.cardRoleLaborant.UseUnderline = true;
            this.vbox3.Add(this.cardRoleLaborant);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox3[this.cardRoleLaborant]));
            w24.Position = 0;
            w24.Expand = false;
            w24.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.cardRoleDoor = new Gtk.CheckButton();
            this.cardRoleDoor.CanFocus = true;
            this.cardRoleDoor.Name = "cardRoleDoor";
            this.cardRoleDoor.Label = Mono.Unix.Catalog.GetString("Türöffner");
            this.cardRoleDoor.DrawIndicator = true;
            this.cardRoleDoor.UseUnderline = true;
            this.vbox3.Add(this.cardRoleDoor);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox3[this.cardRoleDoor]));
            w25.Position = 1;
            w25.Expand = false;
            w25.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.cardRoleCreator = new Gtk.CheckButton();
            this.cardRoleCreator.CanFocus = true;
            this.cardRoleCreator.Name = "cardRoleCreator";
            this.cardRoleCreator.Label = Mono.Unix.Catalog.GetString("(Karten-) Erzeuger");
            this.cardRoleCreator.DrawIndicator = true;
            this.cardRoleCreator.UseUnderline = true;
            this.vbox3.Add(this.cardRoleCreator);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.vbox3[this.cardRoleCreator]));
            w26.Position = 2;
            w26.Expand = false;
            w26.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.cardRoleGod = new Gtk.CheckButton();
            this.cardRoleGod.CanFocus = true;
            this.cardRoleGod.Name = "cardRoleGod";
            this.cardRoleGod.Label = Mono.Unix.Catalog.GetString("Gott");
            this.cardRoleGod.DrawIndicator = true;
            this.cardRoleGod.UseUnderline = true;
            this.vbox3.Add(this.cardRoleGod);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.vbox3[this.cardRoleGod]));
            w27.PackType = ((Gtk.PackType)(1));
            w27.Position = 3;
            w27.Expand = false;
            w27.Fill = false;
            this.table1.Add(this.vbox3);
            Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table1[this.vbox3]));
            w28.TopAttach = ((uint)(2));
            w28.BottomAttach = ((uint)(3));
            w28.LeftAttach = ((uint)(1));
            w28.RightAttach = ((uint)(2));
            w28.XOptions = ((Gtk.AttachOptions)(4));
            w28.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox6.Add(this.table1);
            Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.vbox6[this.table1]));
            w29.Position = 1;
            // Container child vbox6.Gtk.Box+BoxChild
            this.hbuttonbox2 = new Gtk.HButtonBox();
            this.hbuttonbox2.Name = "hbuttonbox2";
            this.hbuttonbox2.BorderWidth = ((uint)(6));
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.cardSaveBtn = new Gtk.Button();
            this.cardSaveBtn.CanFocus = true;
            this.cardSaveBtn.Name = "cardSaveBtn";
            this.cardSaveBtn.UseStock = true;
            this.cardSaveBtn.UseUnderline = true;
            this.cardSaveBtn.Label = "gtk-save";
            this.hbuttonbox2.Add(this.cardSaveBtn);
            Gtk.ButtonBox.ButtonBoxChild w30 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.cardSaveBtn]));
            w30.Expand = false;
            w30.Fill = false;
            this.vbox6.Add(this.hbuttonbox2);
            Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbuttonbox2]));
            w31.Position = 2;
            w31.Expand = false;
            w31.Fill = false;
            this.hpaned1.Add(this.vbox6);
            this.notebook1.Add(this.hpaned1);
            Gtk.Notebook.NotebookChild w33 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.hpaned1]));
            w33.TabFill = false;
            w33.MenuLabel = "";
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Karten");
            this.notebook1.SetTabLabel(this.hpaned1, this.label1);
            this.label1.ShowAll();
            // Notebook tab
            Gtk.Label w34 = new Gtk.Label();
            w34.Visible = true;
            this.notebook1.Add(w34);
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Bestand");
            this.notebook1.SetTabLabel(w34, this.label5);
            this.label5.ShowAll();
            // Notebook tab
            Gtk.Label w35 = new Gtk.Label();
            w35.Visible = true;
            this.notebook1.Add(w35);
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Transaktionen");
            this.notebook1.SetTabLabel(w35, this.label8);
            this.label8.ShowAll();
            this.vbox1.Add(this.notebook1);
            Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
            w36.Position = 1;
            // Container child vbox1.Gtk.Box+BoxChild
            this.statusbar1 = new Gtk.Statusbar();
            this.statusbar1.Name = "statusbar1";
            this.statusbar1.Spacing = 6;
            this.vbox1.Add(this.statusbar1);
            Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
            w37.Position = 2;
            w37.Expand = false;
            w37.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 566;
            this.DefaultHeight = 587;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.button1.Clicked += new System.EventHandler(this.CardAdd);
        }
    }
}
