// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace saftschubser {
    
    
    public partial class KaufenScreen {
        
        private Gtk.HPaned hpaned1;
        
        private saftschubser.ArtikelChooser artikelChooser;
        
        private saftschubser.BestellWidget bestellWidget;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget saftschubser.KaufenScreen
            Stetic.BinContainer.Attach(this);
            this.Name = "saftschubser.KaufenScreen";
            // Container child saftschubser.KaufenScreen.Gtk.Container+ContainerChild
            this.hpaned1 = new Gtk.HPaned();
            this.hpaned1.CanFocus = true;
            this.hpaned1.Name = "hpaned1";
            this.hpaned1.Position = 262;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.artikelChooser = new saftschubser.ArtikelChooser();
            this.artikelChooser.Events = ((Gdk.EventMask)(256));
            this.artikelChooser.Name = "artikelChooser";
            this.artikelChooser.Offset = ((uint)(0));
            this.hpaned1.Add(this.artikelChooser);
            Gtk.Paned.PanedChild w1 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.artikelChooser]));
            w1.Resize = false;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.bestellWidget = new saftschubser.BestellWidget();
            this.bestellWidget.Events = ((Gdk.EventMask)(256));
            this.bestellWidget.Name = "bestellWidget";
            this.hpaned1.Add(this.bestellWidget);
            this.Add(this.hpaned1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.artikelChooser.ArtikelChoosen += new saftschubser.ArtikelChoosenHandler(this.OnArtikelChoosen);
        }
    }
}
