-include common.mk

LIBS     = -lglut -lpthread -lGL -lGLU
CC       = gcc

all: $(OBJ_FOLDER) $(DEP_FOLDER) Makefile common.mk $(PRG) 

$(PRG): $(OBJ_2)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ $(LIBS)

clean:
	rm -rf $(DEP_FOLDER)/ $(OBJ_FOLDER)/ $(PRG) 

-include common_footer.mk
