-include Makefile.inc.common

LIBS     = -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32
CC       = gcc
CFLAGS  += -D_WIN32


all: $(OBJ_FOLDER) $(DEP_FOLDER) Makefile.win Makefile.inc.common $(PRG).exe 

$(PRG).exe: $(OBJ_2)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ $(LIBS)

clean:
	rm -rf $(DEP_FOLDER) .$(OBJ_FOLDER) $(PRG).exe $(PRG).map

default: all
cleandefault: clean

-include Makefile.inc.footer
