-include common.mk

LIBS     = -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32
CC       = gcc
CFLAGS  += -D_WIN32


all: .obj .dep Makefile.win common.mk $(PRG).exe 

$(PRG).exe: $(OBJ_2)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ $(LIBS)

clean:
	rm -rf .dep .obj $(PRG).exe $(PRG).map

default: all
cleandefault: clean

-include common_footer.mk
