-include Makefile.inc.common

LIBS     = -lglut -lpthread -lGL -lGLU
CC       = gcc

all: $(OBJ_FOLDER) $(DEP_FOLDER) Makefile Makefile.inc.common $(PRG) 

$(PRG): $(OBJ_2)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ $(LIBS)

clean:
	rm -rf $(DEP_FOLDER)/ $(OBJ_FOLDER)/ $(PRG) 

-include Makefile.inc.footer
