/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_LaborlichtCtrl (void)
{
  GtkWidget *LaborlichtCtrl;
  GtkWidget *vbox1;
  GtkWidget *hbox1;
  GtkWidget *label2;
  GtkWidget *img_status;
  GtkWidget *label1;
  GtkWidget *addrfield;
  GtkWidget *colorselection;
  GtkWidget *hbox2;
  GtkWidget *btn_;
  GtkWidget *button3;
  GtkWidget *statusbar1;

  LaborlichtCtrl = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (LaborlichtCtrl), _("Laborlicht Ctrl"));
  gtk_window_set_resizable (GTK_WINDOW (LaborlichtCtrl), FALSE);
  gtk_window_set_icon_name (GTK_WINDOW (LaborlichtCtrl), "gtk-dialog-info");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (LaborlichtCtrl), vbox1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  label2 = gtk_label_new (_("Status"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 0);

  img_status = gtk_image_new_from_icon_name ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (img_status);
  gtk_box_pack_start (GTK_BOX (hbox1), img_status, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (img_status), 3, 0);

  label1 = gtk_label_new (_("Device:"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label1), 6, 0);

  addrfield = gtk_entry_new ();
  gtk_widget_show (addrfield);
  gtk_box_pack_start (GTK_BOX (hbox1), addrfield, FALSE, TRUE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (addrfield), 4);
  gtk_entry_set_text (GTK_ENTRY (addrfield), _("0xFF"));
  gtk_entry_set_invisible_char (GTK_ENTRY (addrfield), 9679);
  gtk_entry_set_width_chars (GTK_ENTRY (addrfield), 4);

  colorselection = gtk_color_selection_new ();
  gtk_widget_show (colorselection);
  gtk_box_pack_start (GTK_BOX (vbox1), colorselection, TRUE, TRUE, 0);
  gtk_color_selection_set_has_opacity_control (GTK_COLOR_SELECTION (colorselection), FALSE);
  gtk_color_selection_set_has_palette (GTK_COLOR_SELECTION (colorselection), TRUE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, FALSE, FALSE, 0);

  btn_ = gtk_button_new_with_mnemonic (_("Fade to color"));
  gtk_widget_show (btn_);
  gtk_box_pack_start (GTK_BOX (hbox2), btn_, FALSE, FALSE, 0);

  button3 = gtk_button_new_with_mnemonic (_("Set color"));
  gtk_widget_show (button3);
  gtk_box_pack_start (GTK_BOX (hbox2), button3, FALSE, FALSE, 0);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) LaborlichtCtrl, "destroy_event",
                    G_CALLBACK (llctrl_exit),
                    NULL);
  g_signal_connect ((gpointer) addrfield, "changed",
                    G_CALLBACK (on_addrfield_changed),
                    NULL);
  g_signal_connect ((gpointer) colorselection, "color_changed",
                    G_CALLBACK (on_colorselection_color_changed),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (asjdjasd),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (LaborlichtCtrl, LaborlichtCtrl, "LaborlichtCtrl");
  GLADE_HOOKUP_OBJECT (LaborlichtCtrl, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (LaborlichtCtrl, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (LaborlichtCtrl, label2, "label2");
  GLADE_HOOKUP_OBJECT (LaborlichtCtrl, img_status, "img_status");
  GLADE_HOOKUP_OBJECT (LaborlichtCtrl, label1, "label1");
  GLADE_HOOKUP_OBJECT (LaborlichtCtrl, addrfield, "addrfield");
  GLADE_HOOKUP_OBJECT (LaborlichtCtrl, colorselection, "colorselection");
  GLADE_HOOKUP_OBJECT (LaborlichtCtrl, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (LaborlichtCtrl, btn_, "btn_");
  GLADE_HOOKUP_OBJECT (LaborlichtCtrl, button3, "button3");
  GLADE_HOOKUP_OBJECT (LaborlichtCtrl, statusbar1, "statusbar1");

  return LaborlichtCtrl;
}

