DEFS           = -DF_CPU=16000000 -DNEW_GENERATION
OBJ            = main.o util.o pixel.o games.o basicAnimations.o rotatedAnimations.o randomAnmations.o testPrograms.o scrolltext3.o  borg_hw.o uart.o font_uni53.o joystick.o
CANADDR        = 0x3d

OUT=borg

include ../../make/avr.mk


