ISP_PROG=bsd
#AVRDUDE_BAUDRATE=115200
MCU=atmega8
F_CPU=16000000
DEBUG=0
CFLAGS += -DBOOTLOADER_DDR=DDRC
CFLAGS += -DBOOTLOADER_PORT=PORTC
CFLAGS += -DBOOTLOADER_PIN=PINC
CFLAGS += -DBOOTLOADER_PINNUM=PINC0
CFLAGS += -DSEND_BOOT_MESSAGE=1
CFLAGS += -DBOOTLOADER_CHAR
