#!/bin/sh
#
# keyrona        Starts the Keyrona keyproviderd
#
# chkconfig:   2345 016 88
# description: The Keyrona Keyproviderd
#
# processname: keyrona_keyproviderd
# config:      /etc/keyrona/keyrona.cfg
#
### BEGIN INIT INFO
# Provides: keyrona_keyproviderd
# Required-Start: $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Should-Start: tcsd
# Should-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Keyrona Keyprovider
# Description: The Keyrona Keyprovider
### END INIT INFO

. /etc/init.d/functions

umask 077

EXEC=/usr/sbin/keyrona_keyproviderd
PROG=$(basename $EXEC)
LOCKFILE=/var/lock/subsys/$PROG
KEYRONADIR=/var/run/keyrona
PRUNEOPTION="--prune"

start() {
    echo ""
    echo $"Starting the Keyrona Keyprovider daemon ($PROG): "
    /sbin/pidof $PROG > /dev/null
    retval=$?
    if [ $retval -eq 0 ] && [ -e $KEYRONADIR/server.socket ]
    then
            echo "Keyrona Keyprovider already running."
            exit 0
    fi
    if [ $retval -eq 0 ] && [ ! -e $KEYRONADIR/server.socket ]
    then
            PRUNEOPTION=""
    else
            PRUNEOPTION="--prune"
    fi

    killproc $PROG > /dev/null
    mkdir -p $KEYRONADIR
    chown root:keyrona $KEYRONADIR
    rm -rf $KEYRONADIR/*.socket
    daemon $PROG $PRUNEOPTION
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $LOCKFILE
    return $retval
}
stop() {
    echo -n $"Stopping the Keyrona Keyprovider daemon ($PROG): "
    killproc $PROG
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $LOCKFILE
    return $retval
}
restart() {
    stop
    echo $"Starting the Keyrona Keyprovider daemon ($PROG): "
    daemon $PROG
}


case "$1" in
    start|stop|restart)
        $1
        ;;
    reload|force-reload)
        restart
        ;;
    status)
        status $PROG
        ;;
    condrestart|try-restart)
        [ ! -f $LOCKFILE ] || restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|try-restart|reload|force-reload}"
        exit 2
esac
