
OBJ            = borg_hw.o main.o util.o pixel.o programm.o borg_can.o can.o \
				 spi.o scrolltext3.o font_arial8.o joystick.o snake.o \
				 eeprom_reserve.o persistentCounter.o prng.o
CANADDR        = 0x42

include ../../make/avr.mk


