
AVRXHOME       = ../../lib/AvrX2.6f/avrx/
SRC            = main.c AvrXBufferedSerial.c AvrXFifo.c uart_sw.c server1.c channel.c channels.c dummy_qport.c i2csw.c database.c random.c xcan.c spi.c xlap.c console.c fct_table.c foo.c
MCU_TARGET     = atmega32
DEFS           = -DF_CPU=16000000

include ../../make/avrx.mk
