
OBJ            = borg_hw2.o main.o util.o borg_hw2_asm.o prng.o
# util.o pixel.o programm.o snake.o 

MCU_TARGET    = atmega8
DEFS          = -DF_CPU=8000000

# Fuses, special configured for given MCU
LFUSE = 0xa4
HFUSE = 0xd3

include make/avr_tut.mk
