TARGET = libuip.a
TOPDIR = ..
SRC = \
	psock.c \
	uip_arp.c \
	uip.c \
	uip_multi.c \
	uip_neighbor.c
##############################################################################
# generic fluff
include $(TOPDIR)/defaults.mk
include $(TOPDIR)/rules.mk
