#! /bin/sh

# 2003-08-22 Matthias Ringwald
# parts found in other open source packages

# Run this to generate all the initial makefiles, etc.
# Bootstrap works with automake-1.7 and autoconf-2.57 tools

# It doesn't work with automake-1.4 or 1.5 
# It also requires at least and autoconf-2.54

export WANT_AUTOMAKE=1.7

DIE=0

(autoconf --version) < /dev/null > /dev/null 2>&1 || {
  echo
  echo "**Error**: You must have Autoconf' installed"
  echo "Get version 2.57 or higher from ftp://ftp.gnu.org/pub/gnu/"
  DIE=1
}

(automake --version) < /dev/null > /dev/null 2>&1 || {
  echo
  echo "**Error**: You must have Automake' installed"
  echo "Get version 1.7 or higher from ftp://ftp.gnu.org/pub/gnu/"
  DIE=1
  NO_AUTOMAKE=yes
}

(libtoolize --version) < /dev/null > /dev/null 2>&1 || {
  echo
  echo "**Error**: You must have Libtoolize' installed"
  DIE=1
  NO_LIBTOOLIZE=yes
}

# if no automake, don't bother testing for aclocal
test -n "$NO_AUTOMAKE" || (aclocal --version) < /dev/null > /dev/null 2>&1 || {
  echo
  echo "**Error**: Missing Aclocal'.  The version of Automake'"
  echo "installed doesn't appear recent enough."
  echo "Get version 1.7 or higher from ftp://ftp.gnu.org/pub/gnu/"
  DIE=1
}

if test "$DIE" -eq 1; then
  exit 1
fi

echo "Libtoolize... " &&
libtoolize &&
echo "Running aclocal..." && 
aclocal &&
echo "Running autoheader..." &&
autoheader &&
echo "Running automake..." &&
automake --copy --add-missing &&
echo "Running autoconf..." && 
autoconf &&
echo "Done. Now run ./configure" && exit 0

echo
echo "Failure!"
echo "Check Automake and Autoconf versions"
echo "Automake-1.7 and Autoconf-2.57 are ok"

