######################################################################
# Automatically generated by qmake (2.00a) Tue Mar 28 13:11:02 2006
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CanPacket.h client.h MainWindow.h
FORMS += mainwindow.ui
SOURCES += CanPacket.cpp client.cpp main.cpp MainWindow.cpp
