import sys,glob,os
envlib = Environment(parse_flags='-lusb')
envprog = Environment(LIBPATH = ['./'], CPPPATH = ['./'], parse_flags='-lusb -lmmmuxd')

mmuxdbuild = envlib.SharedLibrary ('mmmuxd', ['muxd.c', 'muxd_client.c', 'muxd_server.c',
	'muxd_hw.c', 'muxd_hw_rfm12usb.c'])
testbuild = envprog.Program ('mmmuxd_test', ['muxd_test.c'])

