
#this is for atmega644
BOOTLOADER_START = 0xfC00
HFUSE            = 0xd6
LFUSE            = 0xd7
EFUSE            = 0xfc



MCU_TARGET     = atmega644

BOOTLOADER_START = 0xfc00

EFUSE = 0xfc
HFUSE = 0xd4
LFUSE = 0xe7

-include canboot_lib/makefile.inc

