// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace serialmon {
    
    
    public partial class ConfigWindow {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Frame frame3;
        
        private Gtk.HBox hbox4;
        
        private Gtk.VBox vbox4;
        
        private Gtk.Table table3;
        
        private Gtk.FontButton fontbutton1;
        
        private Gtk.Label label11;
        
        private Gtk.Frame frame4;
        
        private Gtk.Alignment GtkAlignment6;
        
        private Gtk.Table table4;
        
        private Gtk.RadioButton colauto_rb;
        
        private Gtk.SpinButton colgran_spin;
        
        private Gtk.RadioButton colman_rb;
        
        private Gtk.SpinButton colwidth_spin;
        
        private Gtk.Label label13;
        
        private Gtk.Label label14;
        
        private Gtk.Label GtkLabel8;
        
        private Gtk.Frame frame5;
        
        private Gtk.Alignment GtkAlignment7;
        
        private Gtk.VBox vbox5;
        
        private Gtk.RadioButton addrbasehex_rb;
        
        private Gtk.RadioButton addrbasedec_rb;
        
        private Gtk.RadioButton addrbaseoct_rb;
        
        private Gtk.HBox hbox5;
        
        private Gtk.Label label12;
        
        private Gtk.SpinButton addrwidth_spin;
        
        private Gtk.Label GtkLabel11;
        
        private Gtk.Label GtkLabel9;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Table table1;
        
        private Gtk.ComboBoxEntry cb_baudrate1;
        
        private Gtk.ComboBox cb_databits1;
        
        private Gtk.ComboBox cb_parity1;
        
        private Gtk.ComboBoxEntry cb_pn1;
        
        private Gtk.ComboBox cb_stopbits1;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label label5;
        
        private Gtk.VBox vbox2;
        
        private Gtk.CheckButton checkbutton1;
        
        private Gtk.ColorButton colorbutton1;
        
        private Gtk.Label GtkLabel10;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment3;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Table table2;
        
        private Gtk.ComboBoxEntry cb_baudrate2;
        
        private Gtk.ComboBox cb_databits2;
        
        private Gtk.ComboBox cb_parity2;
        
        private Gtk.ComboBoxEntry cb_pn2;
        
        private Gtk.ComboBox cb_stopbits2;
        
        private Gtk.Label label10;
        
        private Gtk.Label label6;
        
        private Gtk.Label label7;
        
        private Gtk.Label label8;
        
        private Gtk.Label label9;
        
        private Gtk.VBox vbox3;
        
        private Gtk.CheckButton checkbutton2;
        
        private Gtk.ColorButton colorbutton2;
        
        private Gtk.Label GtkLabel13;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Button ok_button;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget serialmon.ConfigWindow
            this.Name = "serialmon.ConfigWindow";
            this.Title = Mono.Unix.Catalog.GetString("ConfigWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.BorderWidth = ((uint)(3));
            // Container child serialmon.ConfigWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame3 = new Gtk.Frame();
            this.frame3.Name = "frame3";
            this.frame3.ShadowType = ((Gtk.ShadowType)(1));
            this.frame3.BorderWidth = ((uint)(3));
            // Container child frame3.Gtk.Container+ContainerChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.table3 = new Gtk.Table(((uint)(1)), ((uint)(2)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.fontbutton1 = new Gtk.FontButton();
            this.fontbutton1.CanFocus = true;
            this.fontbutton1.Name = "fontbutton1";
            this.fontbutton1.FontName = "Monospace 12";
            this.table3.Add(this.fontbutton1);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table3[this.fontbutton1]));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("font");
            this.table3.Add(this.label11);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table3[this.label11]));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox4.Add(this.table3);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox4[this.table3]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.frame4 = new Gtk.Frame();
            this.frame4.Name = "frame4";
            this.frame4.ShadowType = ((Gtk.ShadowType)(1));
            this.frame4.BorderWidth = ((uint)(3));
            // Container child frame4.Gtk.Container+ContainerChild
            this.GtkAlignment6 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment6.Name = "GtkAlignment6";
            this.GtkAlignment6.LeftPadding = ((uint)(12));
            // Container child GtkAlignment6.Gtk.Container+ContainerChild
            this.table4 = new Gtk.Table(((uint)(2)), ((uint)(3)), false);
            this.table4.Name = "table4";
            this.table4.RowSpacing = ((uint)(6));
            this.table4.ColumnSpacing = ((uint)(6));
            // Container child table4.Gtk.Table+TableChild
            this.colauto_rb = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("automatic"));
            this.colauto_rb.CanFocus = true;
            this.colauto_rb.Name = "colauto_rb";
            this.colauto_rb.DrawIndicator = true;
            this.colauto_rb.UseUnderline = true;
            this.colauto_rb.Group = new GLib.SList(System.IntPtr.Zero);
            this.table4.Add(this.colauto_rb);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table4[this.colauto_rb]));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.colgran_spin = new Gtk.SpinButton(1, 100, 1);
            this.colgran_spin.CanFocus = true;
            this.colgran_spin.Name = "colgran_spin";
            this.colgran_spin.Adjustment.PageIncrement = 10;
            this.colgran_spin.ClimbRate = 1;
            this.colgran_spin.Numeric = true;
            this.colgran_spin.Value = 8;
            this.table4.Add(this.colgran_spin);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table4[this.colgran_spin]));
            w5.LeftAttach = ((uint)(2));
            w5.RightAttach = ((uint)(3));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.colman_rb = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("manual"));
            this.colman_rb.CanFocus = true;
            this.colman_rb.Name = "colman_rb";
            this.colman_rb.DrawIndicator = true;
            this.colman_rb.UseUnderline = true;
            this.colman_rb.Group = this.colauto_rb.Group;
            this.table4.Add(this.colman_rb);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table4[this.colman_rb]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.colwidth_spin = new Gtk.SpinButton(1, 100, 1);
            this.colwidth_spin.CanFocus = true;
            this.colwidth_spin.Name = "colwidth_spin";
            this.colwidth_spin.Adjustment.PageIncrement = 10;
            this.colwidth_spin.ClimbRate = 1;
            this.colwidth_spin.Numeric = true;
            this.colwidth_spin.Value = 16;
            this.table4.Add(this.colwidth_spin);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table4[this.colwidth_spin]));
            w7.TopAttach = ((uint)(1));
            w7.BottomAttach = ((uint)(2));
            w7.LeftAttach = ((uint)(2));
            w7.RightAttach = ((uint)(3));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label13 = new Gtk.Label();
            this.label13.Name = "label13";
            this.label13.LabelProp = Mono.Unix.Catalog.GetString("width");
            this.table4.Add(this.label13);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table4[this.label13]));
            w8.TopAttach = ((uint)(1));
            w8.BottomAttach = ((uint)(2));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.label14 = new Gtk.Label();
            this.label14.Name = "label14";
            this.label14.LabelProp = Mono.Unix.Catalog.GetString("granularity");
            this.table4.Add(this.label14);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table4[this.label14]));
            w9.LeftAttach = ((uint)(1));
            w9.RightAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment6.Add(this.table4);
            this.frame4.Add(this.GtkAlignment6);
            this.GtkLabel8 = new Gtk.Label();
            this.GtkLabel8.Name = "GtkLabel8";
            this.GtkLabel8.LabelProp = Mono.Unix.Catalog.GetString("<b>column size</b>");
            this.GtkLabel8.UseMarkup = true;
            this.frame4.LabelWidget = this.GtkLabel8;
            this.vbox4.Add(this.frame4);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox4[this.frame4]));
            w12.Position = 1;
            w12.Expand = false;
            w12.Fill = false;
            this.hbox4.Add(this.vbox4);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox4[this.vbox4]));
            w13.Position = 0;
            w13.Expand = false;
            w13.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.frame5 = new Gtk.Frame();
            this.frame5.Name = "frame5";
            this.frame5.ShadowType = ((Gtk.ShadowType)(1));
            this.frame5.BorderWidth = ((uint)(3));
            // Container child frame5.Gtk.Container+ContainerChild
            this.GtkAlignment7 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment7.Name = "GtkAlignment7";
            this.GtkAlignment7.LeftPadding = ((uint)(12));
            // Container child GtkAlignment7.Gtk.Container+ContainerChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.addrbasehex_rb = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("hexadecimal"));
            this.addrbasehex_rb.CanFocus = true;
            this.addrbasehex_rb.Name = "addrbasehex_rb";
            this.addrbasehex_rb.DrawIndicator = true;
            this.addrbasehex_rb.UseUnderline = true;
            this.addrbasehex_rb.Group = new GLib.SList(System.IntPtr.Zero);
            this.vbox5.Add(this.addrbasehex_rb);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox5[this.addrbasehex_rb]));
            w14.Position = 0;
            w14.Expand = false;
            w14.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.addrbasedec_rb = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("decimal"));
            this.addrbasedec_rb.CanFocus = true;
            this.addrbasedec_rb.Name = "addrbasedec_rb";
            this.addrbasedec_rb.DrawIndicator = true;
            this.addrbasedec_rb.UseUnderline = true;
            this.addrbasedec_rb.Group = this.addrbasehex_rb.Group;
            this.vbox5.Add(this.addrbasedec_rb);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox5[this.addrbasedec_rb]));
            w15.Position = 1;
            w15.Expand = false;
            w15.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.addrbaseoct_rb = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("octal"));
            this.addrbaseoct_rb.Sensitive = false;
            this.addrbaseoct_rb.CanFocus = true;
            this.addrbaseoct_rb.Name = "addrbaseoct_rb";
            this.addrbaseoct_rb.DrawIndicator = true;
            this.addrbaseoct_rb.UseUnderline = true;
            this.addrbaseoct_rb.Group = this.addrbasehex_rb.Group;
            this.vbox5.Add(this.addrbaseoct_rb);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox5[this.addrbaseoct_rb]));
            w16.Position = 2;
            w16.Expand = false;
            w16.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            // Container child hbox5.Gtk.Box+BoxChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.LabelProp = Mono.Unix.Catalog.GetString("width");
            this.hbox5.Add(this.label12);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox5[this.label12]));
            w17.Position = 0;
            w17.Expand = false;
            w17.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.addrwidth_spin = new Gtk.SpinButton(1, 100, 1);
            this.addrwidth_spin.CanFocus = true;
            this.addrwidth_spin.Name = "addrwidth_spin";
            this.addrwidth_spin.Adjustment.PageIncrement = 10;
            this.addrwidth_spin.ClimbRate = 1;
            this.addrwidth_spin.Numeric = true;
            this.addrwidth_spin.Value = 4;
            this.hbox5.Add(this.addrwidth_spin);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox5[this.addrwidth_spin]));
            w18.Position = 1;
            w18.Expand = false;
            w18.Fill = false;
            this.vbox5.Add(this.hbox5);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox5]));
            w19.Position = 3;
            w19.Expand = false;
            w19.Fill = false;
            this.GtkAlignment7.Add(this.vbox5);
            this.frame5.Add(this.GtkAlignment7);
            this.GtkLabel11 = new Gtk.Label();
            this.GtkLabel11.Name = "GtkLabel11";
            this.GtkLabel11.LabelProp = Mono.Unix.Catalog.GetString("<b>address</b>");
            this.GtkLabel11.UseMarkup = true;
            this.frame5.LabelWidget = this.GtkLabel11;
            this.hbox4.Add(this.frame5);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.hbox4[this.frame5]));
            w22.Position = 1;
            w22.Expand = false;
            w22.Fill = false;
            this.frame3.Add(this.hbox4);
            this.GtkLabel9 = new Gtk.Label();
            this.GtkLabel9.Name = "GtkLabel9";
            this.GtkLabel9.LabelProp = Mono.Unix.Catalog.GetString("<b>general settings</b>");
            this.GtkLabel9.UseMarkup = true;
            this.frame3.LabelWidget = this.GtkLabel9;
            this.vbox1.Add(this.frame3);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame3]));
            w24.Position = 0;
            w24.Expand = false;
            w24.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(1));
            this.frame1.BorderWidth = ((uint)(3));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(5)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.cb_baudrate1 = Gtk.ComboBoxEntry.NewText();
            this.cb_baudrate1.AppendText(Mono.Unix.Catalog.GetString("1200"));
            this.cb_baudrate1.AppendText(Mono.Unix.Catalog.GetString("2400"));
            this.cb_baudrate1.AppendText(Mono.Unix.Catalog.GetString("4800"));
            this.cb_baudrate1.AppendText(Mono.Unix.Catalog.GetString("9600"));
            this.cb_baudrate1.AppendText(Mono.Unix.Catalog.GetString("19200"));
            this.cb_baudrate1.AppendText(Mono.Unix.Catalog.GetString("38400"));
            this.cb_baudrate1.AppendText(Mono.Unix.Catalog.GetString("57600"));
            this.cb_baudrate1.AppendText(Mono.Unix.Catalog.GetString("115200"));
            this.cb_baudrate1.Name = "cb_baudrate1";
            this.cb_baudrate1.Active = 3;
            this.table1.Add(this.cb_baudrate1);
            Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table1[this.cb_baudrate1]));
            w25.TopAttach = ((uint)(1));
            w25.BottomAttach = ((uint)(2));
            w25.LeftAttach = ((uint)(1));
            w25.RightAttach = ((uint)(2));
            w25.XOptions = ((Gtk.AttachOptions)(4));
            w25.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.cb_databits1 = Gtk.ComboBox.NewText();
            this.cb_databits1.AppendText(Mono.Unix.Catalog.GetString("5"));
            this.cb_databits1.AppendText(Mono.Unix.Catalog.GetString("6"));
            this.cb_databits1.AppendText(Mono.Unix.Catalog.GetString("7"));
            this.cb_databits1.AppendText(Mono.Unix.Catalog.GetString("8"));
            this.cb_databits1.Name = "cb_databits1";
            this.cb_databits1.Active = 3;
            this.table1.Add(this.cb_databits1);
            Gtk.Table.TableChild w26 = ((Gtk.Table.TableChild)(this.table1[this.cb_databits1]));
            w26.TopAttach = ((uint)(3));
            w26.BottomAttach = ((uint)(4));
            w26.LeftAttach = ((uint)(1));
            w26.RightAttach = ((uint)(2));
            w26.XOptions = ((Gtk.AttachOptions)(4));
            w26.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.cb_parity1 = Gtk.ComboBox.NewText();
            this.cb_parity1.AppendText(Mono.Unix.Catalog.GetString("Even"));
            this.cb_parity1.AppendText(Mono.Unix.Catalog.GetString("Mark"));
            this.cb_parity1.AppendText(Mono.Unix.Catalog.GetString("None"));
            this.cb_parity1.AppendText(Mono.Unix.Catalog.GetString("Odd"));
            this.cb_parity1.AppendText(Mono.Unix.Catalog.GetString("Space"));
            this.cb_parity1.Name = "cb_parity1";
            this.cb_parity1.Active = 2;
            this.table1.Add(this.cb_parity1);
            Gtk.Table.TableChild w27 = ((Gtk.Table.TableChild)(this.table1[this.cb_parity1]));
            w27.TopAttach = ((uint)(2));
            w27.BottomAttach = ((uint)(3));
            w27.LeftAttach = ((uint)(1));
            w27.RightAttach = ((uint)(2));
            w27.XOptions = ((Gtk.AttachOptions)(4));
            w27.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.cb_pn1 = Gtk.ComboBoxEntry.NewText();
            this.cb_pn1.Name = "cb_pn1";
            this.table1.Add(this.cb_pn1);
            Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table1[this.cb_pn1]));
            w28.LeftAttach = ((uint)(1));
            w28.RightAttach = ((uint)(2));
            w28.XOptions = ((Gtk.AttachOptions)(4));
            w28.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.cb_stopbits1 = Gtk.ComboBox.NewText();
            this.cb_stopbits1.AppendText(Mono.Unix.Catalog.GetString("0"));
            this.cb_stopbits1.AppendText(Mono.Unix.Catalog.GetString("1"));
            this.cb_stopbits1.AppendText(Mono.Unix.Catalog.GetString("1.5"));
            this.cb_stopbits1.AppendText(Mono.Unix.Catalog.GetString("2"));
            this.cb_stopbits1.Name = "cb_stopbits1";
            this.cb_stopbits1.Active = 1;
            this.table1.Add(this.cb_stopbits1);
            Gtk.Table.TableChild w29 = ((Gtk.Table.TableChild)(this.table1[this.cb_stopbits1]));
            w29.TopAttach = ((uint)(4));
            w29.BottomAttach = ((uint)(5));
            w29.LeftAttach = ((uint)(1));
            w29.RightAttach = ((uint)(2));
            w29.XOptions = ((Gtk.AttachOptions)(4));
            w29.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("port name");
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w30.XOptions = ((Gtk.AttachOptions)(4));
            w30.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("baudrate");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w31.TopAttach = ((uint)(1));
            w31.BottomAttach = ((uint)(2));
            w31.XOptions = ((Gtk.AttachOptions)(4));
            w31.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("parity");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w32 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w32.TopAttach = ((uint)(2));
            w32.BottomAttach = ((uint)(3));
            w32.XOptions = ((Gtk.AttachOptions)(4));
            w32.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("data bits");
            this.table1.Add(this.label4);
            Gtk.Table.TableChild w33 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
            w33.TopAttach = ((uint)(3));
            w33.BottomAttach = ((uint)(4));
            w33.XOptions = ((Gtk.AttachOptions)(4));
            w33.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("stop bits");
            this.table1.Add(this.label5);
            Gtk.Table.TableChild w34 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
            w34.TopAttach = ((uint)(4));
            w34.BottomAttach = ((uint)(5));
            w34.XOptions = ((Gtk.AttachOptions)(4));
            w34.YOptions = ((Gtk.AttachOptions)(4));
            this.hbox1.Add(this.table1);
            Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.hbox1[this.table1]));
            w35.Position = 0;
            w35.Expand = false;
            w35.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.checkbutton1 = new Gtk.CheckButton();
            this.checkbutton1.CanFocus = true;
            this.checkbutton1.Name = "checkbutton1";
            this.checkbutton1.Label = Mono.Unix.Catalog.GetString("active");
            this.checkbutton1.Active = true;
            this.checkbutton1.DrawIndicator = true;
            this.checkbutton1.UseUnderline = true;
            this.vbox2.Add(this.checkbutton1);
            Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.vbox2[this.checkbutton1]));
            w36.Position = 0;
            w36.Expand = false;
            w36.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.colorbutton1 = new Gtk.ColorButton();
            this.colorbutton1.CanFocus = true;
            this.colorbutton1.Events = ((Gdk.EventMask)(784));
            this.colorbutton1.Name = "colorbutton1";
            this.colorbutton1.Title = Mono.Unix.Catalog.GetString("#FF0000");
            this.vbox2.Add(this.colorbutton1);
            Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.vbox2[this.colorbutton1]));
            w37.Position = 1;
            w37.Expand = false;
            w37.Fill = false;
            this.hbox1.Add(this.vbox2);
            Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
            w38.Position = 1;
            w38.Expand = false;
            w38.Fill = false;
            this.GtkAlignment.Add(this.hbox1);
            this.frame1.Add(this.GtkAlignment);
            this.GtkLabel10 = new Gtk.Label();
            this.GtkLabel10.Name = "GtkLabel10";
            this.GtkLabel10.LabelProp = Mono.Unix.Catalog.GetString("<b>serial port 1</b>");
            this.GtkLabel10.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel10;
            this.vbox1.Add(this.frame1);
            Gtk.Box.BoxChild w41 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
            w41.Position = 1;
            w41.Expand = false;
            w41.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(1));
            this.frame2.BorderWidth = ((uint)(3));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment3.Name = "GtkAlignment3";
            this.GtkAlignment3.LeftPadding = ((uint)(12));
            // Container child GtkAlignment3.Gtk.Container+ContainerChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.table2 = new Gtk.Table(((uint)(5)), ((uint)(2)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.cb_baudrate2 = Gtk.ComboBoxEntry.NewText();
            this.cb_baudrate2.AppendText(Mono.Unix.Catalog.GetString("1200"));
            this.cb_baudrate2.AppendText(Mono.Unix.Catalog.GetString("2400"));
            this.cb_baudrate2.AppendText(Mono.Unix.Catalog.GetString("4800"));
            this.cb_baudrate2.AppendText(Mono.Unix.Catalog.GetString("9600"));
            this.cb_baudrate2.AppendText(Mono.Unix.Catalog.GetString("19200"));
            this.cb_baudrate2.AppendText(Mono.Unix.Catalog.GetString("38400"));
            this.cb_baudrate2.AppendText(Mono.Unix.Catalog.GetString("57600"));
            this.cb_baudrate2.AppendText(Mono.Unix.Catalog.GetString("115200"));
            this.cb_baudrate2.Name = "cb_baudrate2";
            this.cb_baudrate2.Active = 3;
            this.table2.Add(this.cb_baudrate2);
            Gtk.Table.TableChild w42 = ((Gtk.Table.TableChild)(this.table2[this.cb_baudrate2]));
            w42.TopAttach = ((uint)(1));
            w42.BottomAttach = ((uint)(2));
            w42.LeftAttach = ((uint)(1));
            w42.RightAttach = ((uint)(2));
            w42.XOptions = ((Gtk.AttachOptions)(4));
            w42.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.cb_databits2 = Gtk.ComboBox.NewText();
            this.cb_databits2.AppendText(Mono.Unix.Catalog.GetString("5"));
            this.cb_databits2.AppendText(Mono.Unix.Catalog.GetString("6"));
            this.cb_databits2.AppendText(Mono.Unix.Catalog.GetString("7"));
            this.cb_databits2.AppendText(Mono.Unix.Catalog.GetString("8"));
            this.cb_databits2.Name = "cb_databits2";
            this.cb_databits2.Active = 3;
            this.table2.Add(this.cb_databits2);
            Gtk.Table.TableChild w43 = ((Gtk.Table.TableChild)(this.table2[this.cb_databits2]));
            w43.TopAttach = ((uint)(3));
            w43.BottomAttach = ((uint)(4));
            w43.LeftAttach = ((uint)(1));
            w43.RightAttach = ((uint)(2));
            w43.XOptions = ((Gtk.AttachOptions)(4));
            w43.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.cb_parity2 = Gtk.ComboBox.NewText();
            this.cb_parity2.AppendText(Mono.Unix.Catalog.GetString("Even"));
            this.cb_parity2.AppendText(Mono.Unix.Catalog.GetString("Mark"));
            this.cb_parity2.AppendText(Mono.Unix.Catalog.GetString("None"));
            this.cb_parity2.AppendText(Mono.Unix.Catalog.GetString("Odd"));
            this.cb_parity2.AppendText(Mono.Unix.Catalog.GetString("Space"));
            this.cb_parity2.Name = "cb_parity2";
            this.cb_parity2.Active = 2;
            this.table2.Add(this.cb_parity2);
            Gtk.Table.TableChild w44 = ((Gtk.Table.TableChild)(this.table2[this.cb_parity2]));
            w44.TopAttach = ((uint)(2));
            w44.BottomAttach = ((uint)(3));
            w44.LeftAttach = ((uint)(1));
            w44.RightAttach = ((uint)(2));
            w44.XOptions = ((Gtk.AttachOptions)(4));
            w44.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.cb_pn2 = Gtk.ComboBoxEntry.NewText();
            this.cb_pn2.Name = "cb_pn2";
            this.table2.Add(this.cb_pn2);
            Gtk.Table.TableChild w45 = ((Gtk.Table.TableChild)(this.table2[this.cb_pn2]));
            w45.LeftAttach = ((uint)(1));
            w45.RightAttach = ((uint)(2));
            w45.XOptions = ((Gtk.AttachOptions)(4));
            w45.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.cb_stopbits2 = Gtk.ComboBox.NewText();
            this.cb_stopbits2.AppendText(Mono.Unix.Catalog.GetString("0"));
            this.cb_stopbits2.AppendText(Mono.Unix.Catalog.GetString("1"));
            this.cb_stopbits2.AppendText(Mono.Unix.Catalog.GetString("1.5"));
            this.cb_stopbits2.AppendText(Mono.Unix.Catalog.GetString("2"));
            this.cb_stopbits2.Name = "cb_stopbits2";
            this.cb_stopbits2.Active = 1;
            this.table2.Add(this.cb_stopbits2);
            Gtk.Table.TableChild w46 = ((Gtk.Table.TableChild)(this.table2[this.cb_stopbits2]));
            w46.TopAttach = ((uint)(4));
            w46.BottomAttach = ((uint)(5));
            w46.LeftAttach = ((uint)(1));
            w46.RightAttach = ((uint)(2));
            w46.XOptions = ((Gtk.AttachOptions)(4));
            w46.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("port name");
            this.table2.Add(this.label10);
            Gtk.Table.TableChild w47 = ((Gtk.Table.TableChild)(this.table2[this.label10]));
            w47.XOptions = ((Gtk.AttachOptions)(4));
            w47.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("stop bits");
            this.table2.Add(this.label6);
            Gtk.Table.TableChild w48 = ((Gtk.Table.TableChild)(this.table2[this.label6]));
            w48.TopAttach = ((uint)(4));
            w48.BottomAttach = ((uint)(5));
            w48.XOptions = ((Gtk.AttachOptions)(4));
            w48.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("data bits");
            this.table2.Add(this.label7);
            Gtk.Table.TableChild w49 = ((Gtk.Table.TableChild)(this.table2[this.label7]));
            w49.TopAttach = ((uint)(3));
            w49.BottomAttach = ((uint)(4));
            w49.XOptions = ((Gtk.AttachOptions)(4));
            w49.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("parity");
            this.table2.Add(this.label8);
            Gtk.Table.TableChild w50 = ((Gtk.Table.TableChild)(this.table2[this.label8]));
            w50.TopAttach = ((uint)(2));
            w50.BottomAttach = ((uint)(3));
            w50.XOptions = ((Gtk.AttachOptions)(4));
            w50.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("baudrate");
            this.table2.Add(this.label9);
            Gtk.Table.TableChild w51 = ((Gtk.Table.TableChild)(this.table2[this.label9]));
            w51.TopAttach = ((uint)(1));
            w51.BottomAttach = ((uint)(2));
            w51.XOptions = ((Gtk.AttachOptions)(4));
            w51.YOptions = ((Gtk.AttachOptions)(4));
            this.hbox2.Add(this.table2);
            Gtk.Box.BoxChild w52 = ((Gtk.Box.BoxChild)(this.hbox2[this.table2]));
            w52.Position = 0;
            w52.Expand = false;
            w52.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.checkbutton2 = new Gtk.CheckButton();
            this.checkbutton2.CanFocus = true;
            this.checkbutton2.Name = "checkbutton2";
            this.checkbutton2.Label = Mono.Unix.Catalog.GetString("active");
            this.checkbutton2.Active = true;
            this.checkbutton2.DrawIndicator = true;
            this.checkbutton2.UseUnderline = true;
            this.vbox3.Add(this.checkbutton2);
            Gtk.Box.BoxChild w53 = ((Gtk.Box.BoxChild)(this.vbox3[this.checkbutton2]));
            w53.Position = 0;
            w53.Expand = false;
            w53.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.colorbutton2 = new Gtk.ColorButton();
            this.colorbutton2.CanFocus = true;
            this.colorbutton2.Events = ((Gdk.EventMask)(784));
            this.colorbutton2.Name = "colorbutton2";
            this.colorbutton2.Title = Mono.Unix.Catalog.GetString("#FF0000");
            this.vbox3.Add(this.colorbutton2);
            Gtk.Box.BoxChild w54 = ((Gtk.Box.BoxChild)(this.vbox3[this.colorbutton2]));
            w54.Position = 1;
            w54.Expand = false;
            w54.Fill = false;
            this.hbox2.Add(this.vbox3);
            Gtk.Box.BoxChild w55 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
            w55.Position = 1;
            w55.Expand = false;
            w55.Fill = false;
            this.GtkAlignment3.Add(this.hbox2);
            this.frame2.Add(this.GtkAlignment3);
            this.GtkLabel13 = new Gtk.Label();
            this.GtkLabel13.Name = "GtkLabel13";
            this.GtkLabel13.LabelProp = Mono.Unix.Catalog.GetString("<b>serial port 2</b>");
            this.GtkLabel13.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel13;
            this.vbox1.Add(this.frame2);
            Gtk.Box.BoxChild w58 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame2]));
            w58.Position = 2;
            w58.Expand = false;
            w58.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.ok_button = new Gtk.Button();
            this.ok_button.CanFocus = true;
            this.ok_button.Name = "ok_button";
            this.ok_button.UseUnderline = true;
            // Container child ok_button.Gtk.Container+ContainerChild
            Gtk.Alignment w59 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment8.Gtk.Container+ContainerChild
            Gtk.HBox w60 = new Gtk.HBox();
            w60.Spacing = 2;
            // Container child GtkHBox11.Gtk.Container+ContainerChild
            Gtk.Image w61 = new Gtk.Image();
            w61.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Menu, 16);
            w60.Add(w61);
            // Container child GtkHBox11.Gtk.Container+ContainerChild
            Gtk.Label w63 = new Gtk.Label();
            w63.LabelProp = Mono.Unix.Catalog.GetString("OK");
            w63.UseUnderline = true;
            w60.Add(w63);
            w59.Add(w60);
            this.ok_button.Add(w59);
            this.hbox3.Add(this.ok_button);
            Gtk.Box.BoxChild w67 = ((Gtk.Box.BoxChild)(this.hbox3[this.ok_button]));
            w67.Position = 2;
            w67.Expand = false;
            w67.Fill = false;
            this.vbox1.Add(this.hbox3);
            Gtk.Box.BoxChild w68 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
            w68.Position = 3;
            w68.Expand = false;
            w68.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 518;
            this.Show();
            this.DestroyEvent += new Gtk.DestroyEventHandler(this.OnDestroyEvent);
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.fontbutton1.FontSet += new System.EventHandler(this.OnFontbutton1FontSet);
            this.colwidth_spin.ValueChanged += new System.EventHandler(this.OnColwidthSpinValueChanged);
            this.colgran_spin.ValueChanged += new System.EventHandler(this.OnColgranSpinValueChanged);
            this.colauto_rb.GroupChanged += new System.EventHandler(this.OnColautoRbGroupChanged);
            this.addrbasehex_rb.GroupChanged += new System.EventHandler(this.OnAddrbasehexRbGroupChanged);
            this.addrwidth_spin.ValueChanged += new System.EventHandler(this.OnAddrwidthSpinValueChanged);
            this.cb_stopbits1.EditingDone += new System.EventHandler(this.OnCbStopbits1EditingDone);
            this.cb_stopbits1.Changed += new System.EventHandler(this.OnCbStopbits1EditingDone);
            this.cb_pn1.Changed += new System.EventHandler(this.OnCbPn1EditingDone);
            this.cb_parity1.EditingDone += new System.EventHandler(this.OnCbParity1EditingDone);
            this.cb_parity1.Changed += new System.EventHandler(this.OnCbParity1EditingDone);
            this.cb_databits1.EditingDone += new System.EventHandler(this.OnCbDatabits1EditingDone);
            this.cb_databits1.Changed += new System.EventHandler(this.OnCbDatabits1EditingDone);
            this.cb_baudrate1.Changed += new System.EventHandler(this.OnCbBaudrate1EditingDone);
            this.checkbutton1.Released += new System.EventHandler(this.OnCheckbutton1Released);
            this.colorbutton1.ColorSet += new System.EventHandler(this.OnColorbutton1ColorSet);
            this.cb_stopbits2.EditingDone += new System.EventHandler(this.OnCbStopbits2EditingDone);
            this.cb_stopbits2.Changed += new System.EventHandler(this.OnCbStopbits2EditingDone);
            this.cb_pn2.EditingDone += new System.EventHandler(this.OnCbPn2EditingDone);
            this.cb_pn2.Changed += new System.EventHandler(this.OnCbPn2EditingDone);
            this.cb_parity2.EditingDone += new System.EventHandler(this.OnCbParity2EditingDone);
            this.cb_parity2.Changed += new System.EventHandler(this.OnCbParity2EditingDone);
            this.cb_databits2.EditingDone += new System.EventHandler(this.OnCbDatabits2EditingDone);
            this.cb_databits2.Changed += new System.EventHandler(this.OnCbDatabits2EditingDone);
            this.cb_baudrate2.EditingDone += new System.EventHandler(this.OnCbBaudrate2EditingDone);
            this.cb_baudrate2.Changed += new System.EventHandler(this.OnCbBaudrate2EditingDone);
            this.checkbutton2.Released += new System.EventHandler(this.OnCheckbutton2Released);
            this.colorbutton2.ColorSet += new System.EventHandler(this.OnColorbutton2ColorSet);
            this.ok_button.Released += new System.EventHandler(this.OnOKButtonReleased);
        }
    }
}
