#!/bin/sh

. /etc/initrd.default
. /etc/initrd.cryptsetup
. /etc/initrd.lvm
. /etc/initrd.keyrona
. /etc/initrd.tpm

export PATH

mount -t proc proc /proc >/dev/null 2>&1
mount -t sysfs sys /sys >/dev/null 2>&1
mount -o remount,rw / >/dev/null 2>&1

busybox --install -s
echo /sbin/mdev > /proc/sys/kernel/hotplug
echo '0' > /proc/sys/kernel/printk
mdev -s

REAL_ROOT=''
CRYPT_ROOT=''
keymap=''
CMDLINE=`cat /proc/cmdline`
for x in ${CMDLINE}
do
	case "${x}" in
		real_root\=*)
			REAL_ROOT=`parse_opt "${x}"`
		;;
		crypt_root\=*)
			CRYPT_ROOT=`parse_opt "${x}"`
		;;
		keymap\=*)
			keymap=`parse_opt "${x}"`
		;;
	esac
done

#Secure Booting Routine

good_msg "Starting Initramfs"

keymap_check
lvm_check
cryptsetup_check
tpm_initialize
keyrona_login
keyrona_mount_esd 
keyrona_initialize 
keyrona_mount
cleaning_up

#Change to real_root
umount /proc
umount /sys
exec /sbin/switch_root /mnt/root/ /sbin/init

#Urggh not good.
exec sh
