

MCU_TARGET     = atmega128

BOOTLOADER_START = 0x1f800

EFUSE = 0xFF
HFUSE = 0xC4
LFUSE = 0x2F

OPTIMIZE = -Os -fshort-enums -ffunction-sections -fdata-sections -fno-tree-loop-optimize -fno-move-loop-invariants


USER_SRC = user.c



-include canboot_lib/makefile.inc


