
AVRXHOME       = ../../lib/AvrX2.6f/avrx/
SRC            = main.c i2csw.c  asn1.c reader.c borg_hw.c pixel.c 7seg.c panel.c client.c AvrXBufferedSerial.c channel.c channels.c
MCU_TARGET     = atmega32
DEFS           = -DF_CPU=8000000

include avrx.mk
