
AVRXHOME       = ../../lib/AvrX2.6f/avrx/
SRC            = main.c i2csw.c reader.c borg_hw.c panel.c pixel.c 7seg.c client.c AvrXBufferedSerial.c asn1.c channel.c dummy_qport.c
MCU_TARGET     = atmega32
DEFS           = -DF_CPU=8000000

include ../../make/avrx.mk
