
AVRXHOME       = ../../lib/AvrX2.6f/avrx/
SRC            = main.c i2csw.c reader.c borg_hw.c panel.c pixel.c foo.c 7seg.c
MCU_TARGET     = atmega32
DEFS           = -DF_CPU=8000000

include ../../make/avrx.mk
