
OBJ            = borg_hw.o main.o util.o pixel.o programm.o borg_can.o can.o spi.o scrolltext3.o font_arial8.o joystick.o invaders.o invaders_animations.o invaders_draw.o invaders_init.o invaders_shots.o
CANADDR        = 0x42

include ../../make/avr.mk


