
OBJ            = borg_hw.o main.o util.o pixel.o programm.o borg_can.o can.o spi.o scrolltext3.o font_arial8.o joystick.o invaders2.o invader_draw.o invader_proc.o invader_init.o breakpoint.o snake.o

CANADDR        = 0x42

include ../../make/avr.mk


