
#define PORTJOYGND PORTB
#define DDRJOYGND DDRB
#define BITJOY0 PB0
#define BITJOY1 PB1

#define PORTJOYDIRS PORTD
#define DDRJOYDIRS DDRD
#define PINJOYDIRS PIND
#define BITUP PD4
#define BITDOWN PD5
#define BITLEFT PD6
#define BITRIGHT PD7
#define BITFIRE PD3


inline void joy_init(){
	DDRJOYGND |= (1<<BITJOY0)|(1<<BITJOY1);
	PORTJOYGND |= (1<<BITJOY0)|(1<<BITJOY1);

	PORTJOYDIRS |= (1<<BITUP)|(1<<BITDOWN)|(1<<BITLEFT)|(1<<BITRIGHT)|(1<<BITFIRE);
}



#define JOYUSE0() PORTJOYGND |= (1<<BITJOY1); PORTJOYGND &= ~(1<<BITJOY0);
#define JOYUSE1() PORTJOYGND |= (1<<BITJOY0); PORTJOYGND &= ~(1<<BITJOY1);

#define JOYISUP (!(PINJOYDIRS & (1<<BITUP)))
#define JOYISDOWN (!(PINJOYDIRS & (1<<BITDOWN)))
#define JOYISLEFT (!(PINJOYDIRS & (1<<BITLEFT)))
#define JOYISRIGHT (!(PINJOYDIRS & (1<<BITRIGHT)))
#define JOYISFIRE (!(PINJOYDIRS & (1<<BITFIRE)))


