void test1();
void test2();
void test3();
void snake3d();
void snake3dJoystick();
void growingCubeFilled();
void coolAnim();
void matrix();
void spirale();
void spirale2();
void drawLineZAngle(unsigned char angle, unsigned char z, unsigned char value);
void drawLineZ(char x1, char y1, char x2, char y2, char z, char level);
void waves();
void gameOfLife(unsigned char, unsigned int);
void joern1();
void serialStream();
void movingArrows();
void feuer();
void rotatePixmap();
