update=13/6/2009-19:25:52
last_client=cvpcb
[general]
version=1
RootSch=locodoko.sch
BoardNm=locodoko.brd
[common]
NetDir=
[pcbnew]
[pcbnew/libraries]
LibDir=
LibName1=rfm12
LibName2=supports
LibName3=connect
LibName4=discret
LibName5=pin_array
LibName6=divers
LibName7=libcms
LibName8=display
LibName9=valves
[cvpcb]
version=1
NetIExt=.net
[cvpcb/libraries]
EquName1=devcms
