// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Jeton {
    
    
    public partial class ArtikelButtonContent {
        
        private Gtk.HBox hbox1;
        
        private Gtk.Image artikelImage;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label nameLabel;
        
        private Gtk.Label preisLabel;
        
        private Gtk.Label commentLabel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Jeton.ArtikelButtonContent
            Stetic.BinContainer.Attach(this);
            this.Name = "Jeton.ArtikelButtonContent";
            // Container child Jeton.ArtikelButtonContent.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            this.hbox1.BorderWidth = ((uint)(5));
            // Container child hbox1.Gtk.Box+BoxChild
            this.artikelImage = new Gtk.Image();
            this.artikelImage.Name = "artikelImage";
            this.artikelImage.Xpad = 10;
            this.artikelImage.Pixbuf = Gdk.Pixbuf.LoadFromResource("mate.png");
            this.hbox1.Add(this.artikelImage);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.artikelImage]));
            w1.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.nameLabel = new Gtk.Label();
            this.nameLabel.Name = "nameLabel";
            this.nameLabel.Xpad = 5;
            this.nameLabel.Ypad = 2;
            this.nameLabel.Xalign = 0F;
            this.nameLabel.Yalign = 1F;
            this.nameLabel.LabelProp = Mono.Unix.Catalog.GetString("label1");
            this.hbox2.Add(this.nameLabel);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox2[this.nameLabel]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.preisLabel = new Gtk.Label();
            this.preisLabel.Name = "preisLabel";
            this.preisLabel.Ypad = 2;
            this.preisLabel.Yalign = 1F;
            this.preisLabel.LabelProp = Mono.Unix.Catalog.GetString("0.00 €");
            this.hbox2.Add(this.preisLabel);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox2[this.preisLabel]));
            w3.Position = 1;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w4.Position = 0;
            // Container child vbox1.Gtk.Box+BoxChild
            this.commentLabel = new Gtk.Label();
            this.commentLabel.Name = "commentLabel";
            this.commentLabel.Xpad = 5;
            this.commentLabel.Ypad = 2;
            this.commentLabel.Xalign = 0F;
            this.commentLabel.Yalign = 0F;
            this.vbox1.Add(this.commentLabel);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox1[this.commentLabel]));
            w5.Position = 1;
            this.hbox1.Add(this.vbox1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
            w6.Position = 1;
            this.Add(this.hbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
