// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Jeton {
    
    
    public partial class ArtikelChooser {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Button upBtn;
        
        private Gtk.Table btnTable;
        
        private Gtk.Button downBtn;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Jeton.ArtikelChooser
            Stetic.BinContainer.Attach(this);
            this.Name = "Jeton.ArtikelChooser";
            // Container child Jeton.ArtikelChooser.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 16;
            this.vbox2.BorderWidth = ((uint)(12));
            // Container child vbox2.Gtk.Box+BoxChild
            this.upBtn = new Gtk.Button();
            this.upBtn.CanFocus = true;
            this.upBtn.Name = "upBtn";
            this.upBtn.UseUnderline = true;
            // Container child upBtn.Gtk.Container+ContainerChild
            Gtk.Alignment w1 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w2 = new Gtk.HBox();
            w2.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w3 = new Gtk.Image();
            w3.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-up", Gtk.IconSize.Button, 20);
            w2.Add(w3);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w5 = new Gtk.Label();
            w2.Add(w5);
            w1.Add(w2);
            this.upBtn.Add(w1);
            this.vbox2.Add(this.upBtn);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox2[this.upBtn]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.btnTable = new Gtk.Table(((uint)(5)), ((uint)(2)), true);
            this.btnTable.Name = "btnTable";
            this.btnTable.RowSpacing = ((uint)(16));
            this.btnTable.ColumnSpacing = ((uint)(15));
            this.vbox2.Add(this.btnTable);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox2[this.btnTable]));
            w10.Position = 1;
            // Container child vbox2.Gtk.Box+BoxChild
            this.downBtn = new Gtk.Button();
            this.downBtn.CanFocus = true;
            this.downBtn.Name = "downBtn";
            this.downBtn.UseUnderline = true;
            // Container child downBtn.Gtk.Container+ContainerChild
            Gtk.Alignment w11 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w12 = new Gtk.HBox();
            w12.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w13 = new Gtk.Image();
            w13.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-down", Gtk.IconSize.Button, 20);
            w12.Add(w13);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w15 = new Gtk.Label();
            w12.Add(w15);
            w11.Add(w12);
            this.downBtn.Add(w11);
            this.vbox2.Add(this.downBtn);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox2[this.downBtn]));
            w19.Position = 2;
            w19.Expand = false;
            w19.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.upBtn.Clicked += new System.EventHandler(this.OnUpBtnClicked);
            this.downBtn.Clicked += new System.EventHandler(this.OnDownBtnClicked);
        }
    }
}
