// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace saftschubser {
    
    
    public partial class BestandScreen {
        
        private Gtk.Calendar calendar1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget saftschubser.BestandScreen
            Stetic.BinContainer.Attach(this);
            this.Name = "saftschubser.BestandScreen";
            // Container child saftschubser.BestandScreen.Gtk.Container+ContainerChild
            this.calendar1 = new Gtk.Calendar();
            this.calendar1.CanFocus = true;
            this.calendar1.Name = "calendar1";
            this.calendar1.DisplayOptions = ((Gtk.CalendarDisplayOptions)(3));
            this.Add(this.calendar1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
