
OBJ            = main.o util.o pixel.o  scrolltext3.o \
				 font_small6.o borg_hw.o uart.o \
				 snake.o prng.o font_uni53.o
				  
# entfernt: programm.o persistentCounter.o snake.o eeprom_reserve.o prng.o

#MCU_TARGET    = atmega8
MCU_TARGET    = atmega16
DEFS          = -DF_CPU=8000000
include ../../make/avr.mk
