
OBJ            = main.o util.o pixel.o  scrolltext3.o \
				 font_uni53.o borg_hw.o snake.o eeprom_reserve.o \
				  prng.o
# entfernt: programm.o persistentCounter.o

MCU_TARGET    = atmega8
DEFS          = -DF_CPU=8000000
include ../../make/avr.mk



