// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Stetic {
    
    
    internal class Gui {
        
        public static void Build(object obj, System.Type type) {
            Stetic.Gui.Build(obj, type.FullName);
        }
        
        public static void Build(object obj, string id) {
            System.Collections.Hashtable bindings = new System.Collections.Hashtable();
            if ((id == "MainWindow")) {
                Gtk.Window cobj = ((Gtk.Window)(obj));
                // Widget MainWindow
                cobj.Title = "Labor Card Creator";
                Gtk.UIManager w1 = new Gtk.UIManager();
                Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
                Gtk.Action w3 = new Gtk.Action("CardCreator", "_CardCreator", null, null);
                w3.ShortLabel = "_CardCreator";
                bindings["CardCreator"] = w3;
                w2.Add(w3, null);
                Gtk.Action w4 = new Gtk.Action("Help", "_Help", null, null);
                w4.ShortLabel = "_Help";
                bindings["Help"] = w4;
                w2.Add(w4, null);
                Gtk.Action w5 = new Gtk.Action("Quit", "Quit", null, "gtk-quit");
                w5.ShortLabel = "Quit";
                bindings["Quit"] = w5;
                w2.Add(w5, null);
                Gtk.Action w6 = new Gtk.Action("About", "_About...", null, "gtk-about");
                w6.ShortLabel = "_About";
                bindings["About"] = w6;
                w2.Add(w6, null);
                Gtk.Action w7 = new Gtk.Action("ConnectCardTerminal", "Connect Card Terminal...", null, "gtk-connect");
                w7.ShortLabel = "Connect Card Terminal";
                bindings["ConnectCardTerminal"] = w7;
                w2.Add(w7, null);
                Gtk.Action w8 = new Gtk.Action("DisconnectCardTerminal", "Disconnect Card Terminal", null, "gtk-disconnect");
                w8.ShortLabel = "Disconnect Card Terminal";
                bindings["DisconnectCardTerminal"] = w8;
                w2.Add(w8, null);
                Gtk.Action w9 = new Gtk.Action("ViewHexdump", "View _Hexdump...", null, "gtk-justify-fill");
                w9.ShortLabel = "View _Hexdump";
                bindings["ViewHexdump"] = w9;
                w2.Add(w9, null);
                Gtk.Action w10 = new Gtk.Action("EraseCard", "Erase Card...", null, "gtk-clear");
                w10.ShortLabel = "Erase Card...";
                bindings["EraseCard"] = w10;
                w2.Add(w10, null);
                w1.InsertActionGroup(w2, 0);
                cobj.AddAccelGroup(w1.AccelGroup);
                cobj.Icon = Gdk.Pixbuf.LoadFromResource("Labor.png");
                cobj.WindowPosition = ((Gtk.WindowPosition)(4));
                cobj.Events = ((Gdk.EventMask)(0));
                cobj.Name = "MainWindow";
                // Container child MainWindow.Gtk.Container+ContainerChild
                Gtk.VBox w11 = new Gtk.VBox();
                w11.Events = ((Gdk.EventMask)(0));
                w11.Name = "vbox1";
                // Container child vbox1.Gtk.Box+BoxChild
                w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='CardCreator'><menuitem action='ConnectCardTerminal'/><menuitem action='DisconnectCardTerminal'/><menuitem action='ViewHexdump'/><menuitem action='EraseCard'/><menuitem action='Quit'/></menu><menu action='Help'><menuitem action='About'/></menu></menubar></ui>");
                Gtk.MenuBar w12 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
                w12.Events = ((Gdk.EventMask)(0));
                w12.Name = "menubar1";
                bindings["menubar1"] = w12;
                w11.Add(w12);
                Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(w11[w12]));
                w13.Position = 0;
                w13.Expand = false;
                w13.Fill = false;
                // Container child vbox1.Gtk.Box+BoxChild
                Gtk.Table w14 = new Gtk.Table(((uint)(4)), ((uint)(2)), false);
                w14.RowSpacing = ((uint)(6));
                w14.ColumnSpacing = ((uint)(10));
                w14.BorderWidth = ((uint)(6));
                w14.Events = ((Gdk.EventMask)(0));
                w14.Name = "table2";
                // Container child table2.Gtk.Table+TableChild
                Gtk.Entry w15 = new Gtk.Entry();
                Gtk.Tooltips w16 = new Gtk.Tooltips();
                w16.SetTip(w15, "Internal Card Number", "Internal Card Number");
                w15.Text = "2342";
                w15.IsEditable = false;
                w15.InvisibleChar = '●';
                w15.CanFocus = true;
                w15.Events = ((Gdk.EventMask)(0));
                w15.Name = "numberEntry";
                w15.Sensitive = false;
                bindings["numberEntry"] = w15;
                w14.Add(w15);
                Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(w14[w15]));
                w17.BottomAttach = ((uint)(3));
                w17.LeftAttach = ((uint)(1));
                w17.RightAttach = ((uint)(2));
                w17.TopAttach = ((uint)(2));
                w17.YOptions = ((Gtk.AttachOptions)(4));
                w17.XOptions = ((Gtk.AttachOptions)(4));
                // Container child table2.Gtk.Table+TableChild
                Gtk.Entry w18 = new Gtk.Entry();
                w18.IsEditable = true;
                w18.InvisibleChar = '●';
                w18.CanFocus = true;
                w18.Events = ((Gdk.EventMask)(0));
                w18.Name = "nameEntry";
                bindings["nameEntry"] = w18;
                w14.Add(w18);
                Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(w14[w18]));
                w19.BottomAttach = ((uint)(2));
                w19.LeftAttach = ((uint)(1));
                w19.RightAttach = ((uint)(2));
                w19.TopAttach = ((uint)(1));
                w19.YOptions = ((Gtk.AttachOptions)(4));
                w19.XOptions = ((Gtk.AttachOptions)(4));
                // Container child table2.Gtk.Table+TableChild
                Gtk.Entry w20 = new Gtk.Entry();
                w20.IsEditable = true;
                w20.WidthChars = 7;
                w20.MaxLength = 7;
                w20.InvisibleChar = '●';
                w20.CanFocus = true;
                w20.Events = ((Gdk.EventMask)(0));
                w20.Name = "nickEntry";
                bindings["nickEntry"] = w20;
                w14.Add(w20);
                Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(w14[w20]));
                w21.LeftAttach = ((uint)(1));
                w21.RightAttach = ((uint)(2));
                w21.YOptions = ((Gtk.AttachOptions)(4));
                // Container child table2.Gtk.Table+TableChild
                Gtk.Label w22 = new Gtk.Label();
                w22.LabelProp = "Card Number:";
                w22.UseUnderline = true;
                w22.Xalign = 1F;
                w22.Events = ((Gdk.EventMask)(0));
                w22.Name = "label3";
                bindings["label3"] = w22;
                w14.Add(w22);
                Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(w14[w22]));
                w23.BottomAttach = ((uint)(3));
                w23.TopAttach = ((uint)(2));
                w23.YOptions = ((Gtk.AttachOptions)(4));
                w23.XOptions = ((Gtk.AttachOptions)(4));
                // Container child table2.Gtk.Table+TableChild
                Gtk.Label w24 = new Gtk.Label();
                w24.LabelProp = "Real N_ame:";
                w24.UseUnderline = true;
                w24.Xalign = 1F;
                w24.Events = ((Gdk.EventMask)(0));
                w24.Name = "label2";
                bindings["label2"] = w24;
                w14.Add(w24);
                Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(w14[w24]));
                w25.BottomAttach = ((uint)(2));
                w25.TopAttach = ((uint)(1));
                w25.YOptions = ((Gtk.AttachOptions)(4));
                w25.XOptions = ((Gtk.AttachOptions)(4));
                // Container child table2.Gtk.Table+TableChild
                Gtk.Label w26 = new Gtk.Label();
                w26.LabelProp = "_Nick:";
                w26.UseUnderline = true;
                w26.Xalign = 1F;
                w26.Events = ((Gdk.EventMask)(0));
                w26.Name = "label4";
                bindings["label4"] = w26;
                w14.Add(w26);
                Gtk.Table.TableChild w27 = ((Gtk.Table.TableChild)(w14[w26]));
                w27.YOptions = ((Gtk.AttachOptions)(4));
                w27.XOptions = ((Gtk.AttachOptions)(4));
                // Container child table2.Gtk.Table+TableChild
                Gtk.Label w28 = new Gtk.Label();
                w28.LabelProp = "Permissions:";
                w28.UseUnderline = true;
                w28.Xalign = 1F;
                w28.Events = ((Gdk.EventMask)(0));
                w28.Name = "label1";
                bindings["label1"] = w28;
                w14.Add(w28);
                Gtk.Table.TableChild w29 = ((Gtk.Table.TableChild)(w14[w28]));
                w29.BottomAttach = ((uint)(4));
                w29.TopAttach = ((uint)(3));
                w29.YOptions = ((Gtk.AttachOptions)(4));
                w29.XOptions = ((Gtk.AttachOptions)(4));
                // Container child table2.Gtk.Table+TableChild
                Gtk.HBox w30 = new Gtk.HBox();
                w30.Events = ((Gdk.EventMask)(0));
                w30.Name = "hbox2";
                // Container child hbox2.Gtk.Box+BoxChild
                Gtk.CheckButton w31 = new Gtk.CheckButton();
                w31.Label = "Admin";
                w31.DrawIndicator = true;
                w31.CanFocus = true;
                w31.Events = ((Gdk.EventMask)(0));
                w31.Name = "adminCheck";
                w31.Sensitive = false;
                bindings["adminCheck"] = w31;
                w30.Add(w31);
                Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(w30[w31]));
                w32.Position = 0;
                // Container child hbox2.Gtk.Box+BoxChild
                Gtk.CheckButton w33 = new Gtk.CheckButton();
                w33.Label = "Door 0";
                w33.Active = true;
                w33.DrawIndicator = true;
                w33.CanFocus = true;
                w33.Events = ((Gdk.EventMask)(0));
                w33.Name = "door0Check";
                bindings["door0Check"] = w33;
                w30.Add(w33);
                Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(w30[w33]));
                w34.Position = 1;
                // Container child hbox2.Gtk.Box+BoxChild
                Gtk.CheckButton w35 = new Gtk.CheckButton();
                w35.Label = "Door 1";
                w35.Active = true;
                w35.DrawIndicator = true;
                w35.CanFocus = true;
                w35.Events = ((Gdk.EventMask)(0));
                w35.Name = "door1Check";
                bindings["door1Check"] = w35;
                w30.Add(w35);
                Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(w30[w35]));
                w36.Position = 2;
                bindings["hbox2"] = w30;
                w14.Add(w30);
                Gtk.Table.TableChild w37 = ((Gtk.Table.TableChild)(w14[w30]));
                w37.BottomAttach = ((uint)(4));
                w37.LeftAttach = ((uint)(1));
                w37.RightAttach = ((uint)(2));
                w37.TopAttach = ((uint)(3));
                w37.YOptions = ((Gtk.AttachOptions)(4));
                w37.XOptions = ((Gtk.AttachOptions)(4));
                bindings["table2"] = w14;
                w11.Add(w14);
                Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(w11[w14]));
                w38.Position = 1;
                w38.Expand = false;
                w38.Fill = false;
                // Container child vbox1.Gtk.Box+BoxChild
                Gtk.Statusbar w39 = new Gtk.Statusbar();
                w39.HasResizeGrip = false;
                w39.Events = ((Gdk.EventMask)(0));
                w39.Name = "statusbar1";
                bindings["statusbar1"] = w39;
                w11.Add(w39);
                Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(w11[w39]));
                w40.PackType = ((Gtk.PackType)(1));
                w40.Position = 2;
                w40.Expand = false;
                w40.Fill = false;
                // Container child vbox1.Gtk.Box+BoxChild
                Gtk.HBox w41 = new Gtk.HBox();
                w41.Events = ((Gdk.EventMask)(0));
                w41.Name = "hbox3";
                // Container child hbox3.Gtk.Box+BoxChild
                Gtk.Image w42 = new Gtk.Image();
                w42.Pixbuf = Gdk.Pixbuf.LoadFromResource("Labor.png");
                w42.Events = ((Gdk.EventMask)(0));
                w42.Name = "image11";
                bindings["image11"] = w42;
                w41.Add(w42);
                Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(w41[w42]));
                w43.Position = 0;
                w43.Expand = false;
                w43.Fill = false;
                w43.Padding = ((uint)(30));
                // Container child hbox3.Gtk.Box+BoxChild
                Gtk.HBox w44 = new Gtk.HBox();
                w44.Events = ((Gdk.EventMask)(0));
                w44.Name = "hbox1";
                // Container child hbox1.Gtk.Box+BoxChild
                Gtk.HButtonBox w45 = new Gtk.HButtonBox();
                w45.Spacing = 20;
                w45.BorderWidth = ((uint)(11));
                w45.Events = ((Gdk.EventMask)(0));
                w45.Name = "hbuttonbox1";
                // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
                Gtk.Button w46 = new Gtk.Button();
                w46.UseUnderline = true;
                w46.CanFocus = true;
                w46.Events = ((Gdk.EventMask)(0));
                w46.Name = "writeBtn";
                w46.HasDefault = true;
                w46.CanDefault = true;
                // Container child writeBtn.Gtk.Container+ContainerChild
                Gtk.Alignment w47 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
                w47.Events = ((Gdk.EventMask)(0));
                w47.Name = "GtkAlignment";
                // Container child GtkAlignment.Gtk.Container+ContainerChild
                Gtk.HBox w48 = new Gtk.HBox();
                w48.Spacing = 2;
                w48.Events = ((Gdk.EventMask)(0));
                w48.Name = "GtkHBox";
                // Container child GtkHBox.Gtk.Container+ContainerChild
                Gtk.Image w49 = new Gtk.Image();
                w49.Pixbuf = Gtk.IconTheme.Default.LoadIcon("stock_creditcard", 16, 0);
                w49.Events = ((Gdk.EventMask)(0));
                w49.Name = "image1";
                bindings["image1"] = w49;
                w48.Add(w49);
                // Container child GtkHBox.Gtk.Container+ContainerChild
                Gtk.Label w51 = new Gtk.Label();
                w51.LabelProp = "_Write to card";
                w51.UseUnderline = true;
                w51.Events = ((Gdk.EventMask)(0));
                w51.Name = "GtkLabel";
                bindings["GtkLabel"] = w51;
                w48.Add(w51);
                bindings["GtkHBox"] = w48;
                w47.Add(w48);
                bindings["GtkAlignment"] = w47;
                w46.Add(w47);
                bindings["writeBtn"] = w46;
                w45.Add(w46);
                Gtk.ButtonBox.ButtonBoxChild w55 = ((Gtk.ButtonBox.ButtonBoxChild)(w45[w46]));
                w55.Expand = false;
                w55.Fill = false;
                bindings["hbuttonbox1"] = w45;
                w44.Add(w45);
                Gtk.Box.BoxChild w56 = ((Gtk.Box.BoxChild)(w44[w45]));
                w56.Position = 0;
                bindings["hbox1"] = w44;
                w41.Add(w44);
                Gtk.Box.BoxChild w57 = ((Gtk.Box.BoxChild)(w41[w44]));
                w57.Position = 1;
                bindings["hbox3"] = w41;
                w11.Add(w41);
                Gtk.Box.BoxChild w58 = ((Gtk.Box.BoxChild)(w11[w41]));
                w58.PackType = ((Gtk.PackType)(1));
                w58.Position = 3;
                w58.Expand = false;
                w58.Fill = false;
                bindings["vbox1"] = w11;
                cobj.Add(w11);
                cobj.DefaultWidth = 516;
                cobj.DefaultHeight = 287;
                bindings["MainWindow"] = cobj;
                w12.Show();
                w15.Show();
                w18.Show();
                w20.Show();
                w22.Show();
                w24.Show();
                w26.Show();
                w28.Show();
                w31.Show();
                w33.Show();
                w35.Show();
                w30.Show();
                w14.Show();
                w39.Show();
                w42.Show();
                w49.Show();
                w51.Show();
                w48.Show();
                w47.Show();
                w46.Show();
                w45.Show();
                w44.Show();
                w41.Show();
                w11.Show();
                cobj.Show();
                cobj.DeleteEvent += ((Gtk.DeleteEventHandler)(System.Delegate.CreateDelegate(typeof(Gtk.DeleteEventHandler), cobj, "OnDeleteEvent")));
                w5.Activated += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnQuitActivated")));
                w6.Activated += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnAboutActivated")));
                w7.Activated += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnConnectActivated")));
                w8.Activated += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnDisconnectActivated")));
                w9.Activated += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnViewHexdumpActivated")));
                w10.Activated += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnEraseActivated")));
                w46.Clicked += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnWriteBtnClicked")));
            }
            System.Reflection.FieldInfo[] fields = obj.GetType().GetFields(((System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic) | System.Reflection.BindingFlags.Instance));
            for (int n = 0; (n < fields.Length); n = (n + 1)) {
                System.Reflection.FieldInfo field = fields[n];
                object widget = bindings[field.Name];
                if (((widget != null) && field.FieldType.IsInstanceOfType(widget))) {
                    field.SetValue(obj, widget);
                }
            }
        }
    }
    
    internal class ActionGroups {
        
        public static Gtk.ActionGroup GetActionGroup(System.Type type) {
            return Stetic.ActionGroups.GetActionGroup(type.FullName);
        }
        
        public static Gtk.ActionGroup GetActionGroup(string name) {
            return null;
        }
    }
}
