import sys,glob,os
envprog = Environment(LIBPATH = ['./'], CPPPATH = ['./'], parse_flags='-lusb -lmmmuxd')

mmuxdbuild = envlib.SharedLibrary ('mmmuxd', ['muxd.c', 'muxd_client.c', 'muxd_server.c','muxd_hw.c', 'muxd_hw_rfm12usb.c', 'muxd_hw_dummy.c'])
statusmonbuild = envprog.Program ('statusmonitor', ['statusmonitor.c'])
