
#define TICK_CHARGE_START 0
#define TICK_END_OF_CHARGE 30
#define TICK_CHARGE_STOP 32
#define TICK_PULSE_ON 34
#define TICK_PULSE_OFF 35
#define TICK_SEQUENCE_COUNT (TICK_CHARGE_START + TICK_END_OF_CHARGE + TICK_CHARGE_STOP + TICK_PULSE_ON + TICK_PULSE_OFF)

#define MIN_FIRE_PERIOD 50  /*50ms = 20Hz*/


void init_pulse(void);
