// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace sermon2 {
    
    
    public partial class TaggerDataConf {
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Table table1;
        
        private Gtk.CheckButton backgroundCheckButton;
        
        private Gtk.ColorButton backgroundColorButton;
        
        private Gtk.CheckButton foregroundCheckButton;
        
        private Gtk.ColorButton foregroundColorButton;
        
        private Gtk.Button remButton;
        
        private Gtk.Label dataLabel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget sermon2.TaggerDataConf
            Stetic.BinContainer.Attach(this);
            this.Name = "sermon2.TaggerDataConf";
            // Container child sermon2.TaggerDataConf.Gtk.Container+ContainerChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(1));
            this.frame1.BorderWidth = ((uint)(3));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            this.table1.BorderWidth = ((uint)(3));
            // Container child table1.Gtk.Table+TableChild
            this.backgroundCheckButton = new Gtk.CheckButton();
            this.backgroundCheckButton.CanFocus = true;
            this.backgroundCheckButton.Name = "backgroundCheckButton";
            this.backgroundCheckButton.Label = Mono.Unix.Catalog.GetString("background");
            this.backgroundCheckButton.DrawIndicator = true;
            this.backgroundCheckButton.UseUnderline = true;
            this.table1.Add(this.backgroundCheckButton);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.backgroundCheckButton]));
            w1.TopAttach = ((uint)(1));
            w1.BottomAttach = ((uint)(2));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.backgroundColorButton = new Gtk.ColorButton();
            this.backgroundColorButton.CanFocus = true;
            this.backgroundColorButton.Events = ((Gdk.EventMask)(784));
            this.backgroundColorButton.Name = "backgroundColorButton";
            this.backgroundColorButton.Title = Mono.Unix.Catalog.GetString("#000000");
            this.table1.Add(this.backgroundColorButton);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.backgroundColorButton]));
            w2.TopAttach = ((uint)(1));
            w2.BottomAttach = ((uint)(2));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.foregroundCheckButton = new Gtk.CheckButton();
            this.foregroundCheckButton.CanFocus = true;
            this.foregroundCheckButton.Name = "foregroundCheckButton";
            this.foregroundCheckButton.Label = Mono.Unix.Catalog.GetString("foreground");
            this.foregroundCheckButton.DrawIndicator = true;
            this.foregroundCheckButton.UseUnderline = true;
            this.table1.Add(this.foregroundCheckButton);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.foregroundCheckButton]));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.foregroundColorButton = new Gtk.ColorButton();
            this.foregroundColorButton.CanFocus = true;
            this.foregroundColorButton.Events = ((Gdk.EventMask)(784));
            this.foregroundColorButton.Name = "foregroundColorButton";
            this.table1.Add(this.foregroundColorButton);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.foregroundColorButton]));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox3.Add(this.table1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox3[this.table1]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.remButton = new Gtk.Button();
            this.remButton.CanFocus = true;
            this.remButton.Name = "remButton";
            this.remButton.UseUnderline = true;
            this.remButton.BorderWidth = ((uint)(3));
            // Container child remButton.Gtk.Container+ContainerChild
            Gtk.Alignment w6 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w7 = new Gtk.HBox();
            w7.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w8 = new Gtk.Image();
            w8.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
            w7.Add(w8);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w10 = new Gtk.Label();
            w10.LabelProp = Mono.Unix.Catalog.GetString("remove");
            w10.UseUnderline = true;
            w7.Add(w10);
            w6.Add(w7);
            this.remButton.Add(w6);
            this.vbox3.Add(this.remButton);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox3[this.remButton]));
            w14.Position = 1;
            w14.Expand = false;
            w14.Fill = false;
            this.GtkAlignment.Add(this.vbox3);
            this.frame1.Add(this.GtkAlignment);
            this.dataLabel = new Gtk.Label();
            this.dataLabel.Name = "dataLabel";
            this.dataLabel.LabelProp = Mono.Unix.Catalog.GetString("<b>data tagger</b>");
            this.dataLabel.UseMarkup = true;
            this.frame1.LabelWidget = this.dataLabel;
            this.Add(this.frame1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.foregroundColorButton.ColorSet += new System.EventHandler(this.OnForegroundColorButtonColorSet);
            this.foregroundCheckButton.Released += new System.EventHandler(this.OnForegroundCheckButtonReleased);
            this.backgroundColorButton.ColorSet += new System.EventHandler(this.OnBackgroundColorButtonColorSet);
            this.backgroundCheckButton.Released += new System.EventHandler(this.OnBackgroundCheckButtonReleased);
            this.remButton.Released += new System.EventHandler(this.OnRemButtonReleased);
        }
    }
}
