// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace sermon2 {
    
    
    public partial class MainWindow {
        
        private Gtk.VBox vbox2;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.Notebook notebook1;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox2;
        
        private Gtk.ComboBox objectAddComboBox;
        
        private Gtk.Button NewObjButton;
        
        private Gtk.Label label1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Button button1;
        
        private Gtk.Button button24;
        
        private Gtk.Statusbar statusbar2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget sermon2.MainWindow
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "sermon2.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("MainWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.BorderWidth = ((uint)(3));
            // Container child sermon2.MainWindow.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><menubar name='menubar1'/></ui>");
            this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox2.Add(this.menubar1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.menubar1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 0;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            Gtk.Viewport w4 = new Gtk.Viewport();
            w4.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.objectAddComboBox = Gtk.ComboBox.NewText();
            this.objectAddComboBox.AppendText(Mono.Unix.Catalog.GetString("serial port"));
            this.objectAddComboBox.AppendText(Mono.Unix.Catalog.GetString("tagger"));
            this.objectAddComboBox.AppendText(Mono.Unix.Catalog.GetString("lop"));
            this.objectAddComboBox.AppendText(Mono.Unix.Catalog.GetString("qport"));
            this.objectAddComboBox.AppendText(Mono.Unix.Catalog.GetString("streamview"));
            this.objectAddComboBox.AppendText(Mono.Unix.Catalog.GetString("lopview"));
            this.objectAddComboBox.Name = "objectAddComboBox";
            this.objectAddComboBox.Active = 0;
            this.hbox2.Add(this.objectAddComboBox);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.objectAddComboBox]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.NewObjButton = new Gtk.Button();
            this.NewObjButton.CanFocus = true;
            this.NewObjButton.Name = "NewObjButton";
            this.NewObjButton.UseUnderline = true;
            // Container child NewObjButton.Gtk.Container+ContainerChild
            Gtk.Alignment w6 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w7 = new Gtk.HBox();
            w7.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w8 = new Gtk.Image();
            w8.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
            w7.Add(w8);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w10 = new Gtk.Label();
            w10.LabelProp = Mono.Unix.Catalog.GetString("new object");
            w10.UseUnderline = true;
            w7.Add(w10);
            w6.Add(w7);
            this.NewObjButton.Add(w6);
            this.hbox2.Add(this.NewObjButton);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox2[this.NewObjButton]));
            w14.Position = 1;
            w14.Expand = false;
            w14.Fill = false;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w15.PackType = ((Gtk.PackType)(1));
            w15.Position = 2;
            w15.Expand = false;
            w15.Fill = false;
            w4.Add(this.vbox1);
            this.scrolledwindow1.Add(w4);
            this.notebook1.Add(this.scrolledwindow1);
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("objects");
            this.notebook1.SetTabLabel(this.scrolledwindow1, this.label1);
            this.label1.ShowAll();
            this.vbox2.Add(this.notebook1);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox2[this.notebook1]));
            w19.Position = 1;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.button1 = new Gtk.Button();
            this.button1.CanFocus = true;
            this.button1.Name = "button1";
            this.button1.UseUnderline = true;
            this.button1.Label = Mono.Unix.Catalog.GetString("button1");
            this.hbox1.Add(this.button1);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox1[this.button1]));
            w20.Position = 0;
            w20.Expand = false;
            w20.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.button24 = new Gtk.Button();
            this.button24.CanFocus = true;
            this.button24.Name = "button24";
            this.button24.UseUnderline = true;
            this.button24.Label = Mono.Unix.Catalog.GetString("button24");
            this.hbox1.Add(this.button24);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox1[this.button24]));
            w21.Position = 1;
            w21.Expand = false;
            w21.Fill = false;
            this.vbox2.Add(this.hbox1);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
            w22.Position = 2;
            w22.Expand = false;
            w22.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.statusbar2 = new Gtk.Statusbar();
            this.statusbar2.Name = "statusbar2";
            this.statusbar2.Spacing = 6;
            this.vbox2.Add(this.statusbar2);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox2[this.statusbar2]));
            w23.Position = 3;
            w23.Expand = false;
            w23.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.NewObjButton.Released += new System.EventHandler(this.OnNewObjButtonReleased);
            this.button1.Released += new System.EventHandler(this.OnButton1Released);
            this.button24.Released += new System.EventHandler(this.OnButton24Released);
        }
    }
}
