// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace sermon2 {
    
    
    public partial class TaggerConf {
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Table table1;
        
        private Gtk.ColorButton backgroundCButton;
        
        private Gtk.CheckButton backgroundCheckButton;
        
        private Gtk.CheckButton dataCheckButton;
        
        private Gtk.ColorButton foregroundCButton;
        
        private Gtk.CheckButton foregroundCheckButton;
        
        private Gtk.Button removeButton;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment5;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Button addTaggerDataConfbutton;
        
        private Gtk.Label GtkLabel5;
        
        private Gtk.Label frameLabel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget sermon2.TaggerConf
            Stetic.BinContainer.Attach(this);
            this.Name = "sermon2.TaggerConf";
            // Container child sermon2.TaggerConf.Gtk.Container+ContainerChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.backgroundCButton = new Gtk.ColorButton();
            this.backgroundCButton.CanFocus = true;
            this.backgroundCButton.Events = ((Gdk.EventMask)(784));
            this.backgroundCButton.Name = "backgroundCButton";
            this.table1.Add(this.backgroundCButton);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.backgroundCButton]));
            w1.TopAttach = ((uint)(1));
            w1.BottomAttach = ((uint)(2));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.XOptions = ((Gtk.AttachOptions)(0));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.backgroundCheckButton = new Gtk.CheckButton();
            this.backgroundCheckButton.CanFocus = true;
            this.backgroundCheckButton.Name = "backgroundCheckButton";
            this.backgroundCheckButton.Label = Mono.Unix.Catalog.GetString("background");
            this.backgroundCheckButton.DrawIndicator = true;
            this.backgroundCheckButton.UseUnderline = true;
            this.table1.Add(this.backgroundCheckButton);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.backgroundCheckButton]));
            w2.TopAttach = ((uint)(1));
            w2.BottomAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.dataCheckButton = new Gtk.CheckButton();
            this.dataCheckButton.CanFocus = true;
            this.dataCheckButton.Name = "dataCheckButton";
            this.dataCheckButton.Label = Mono.Unix.Catalog.GetString("data dependant");
            this.dataCheckButton.DrawIndicator = true;
            this.dataCheckButton.UseUnderline = true;
            this.table1.Add(this.dataCheckButton);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.dataCheckButton]));
            w3.TopAttach = ((uint)(2));
            w3.BottomAttach = ((uint)(3));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.foregroundCButton = new Gtk.ColorButton();
            this.foregroundCButton.CanFocus = true;
            this.foregroundCButton.Events = ((Gdk.EventMask)(784));
            this.foregroundCButton.Name = "foregroundCButton";
            this.table1.Add(this.foregroundCButton);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.foregroundCButton]));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(0));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.foregroundCheckButton = new Gtk.CheckButton();
            this.foregroundCheckButton.CanFocus = true;
            this.foregroundCheckButton.Name = "foregroundCheckButton";
            this.foregroundCheckButton.Label = Mono.Unix.Catalog.GetString("foreground");
            this.foregroundCheckButton.DrawIndicator = true;
            this.foregroundCheckButton.UseUnderline = true;
            this.table1.Add(this.foregroundCheckButton);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.foregroundCheckButton]));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.removeButton = new Gtk.Button();
            this.removeButton.CanFocus = true;
            this.removeButton.Name = "removeButton";
            this.removeButton.UseUnderline = true;
            // Container child removeButton.Gtk.Container+ContainerChild
            Gtk.Alignment w6 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w7 = new Gtk.HBox();
            w7.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w8 = new Gtk.Image();
            w8.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-delete", Gtk.IconSize.Menu, 16);
            w7.Add(w8);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w10 = new Gtk.Label();
            w10.LabelProp = Mono.Unix.Catalog.GetString("remove");
            w10.UseUnderline = true;
            w7.Add(w10);
            w6.Add(w7);
            this.removeButton.Add(w6);
            this.table1.Add(this.removeButton);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.removeButton]));
            w14.TopAttach = ((uint)(2));
            w14.BottomAttach = ((uint)(3));
            w14.LeftAttach = ((uint)(1));
            w14.RightAttach = ((uint)(2));
            w14.XOptions = ((Gtk.AttachOptions)(0));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox3.Add(this.table1);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox3[this.table1]));
            w15.Position = 0;
            w15.Expand = false;
            w15.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(1));
            this.frame2.BorderWidth = ((uint)(6));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment5 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment5.Name = "GtkAlignment5";
            this.GtkAlignment5.LeftPadding = ((uint)(12));
            // Container child GtkAlignment5.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.addTaggerDataConfbutton = new Gtk.Button();
            this.addTaggerDataConfbutton.CanFocus = true;
            this.addTaggerDataConfbutton.Name = "addTaggerDataConfbutton";
            this.addTaggerDataConfbutton.UseUnderline = true;
            // Container child addTaggerDataConfbutton.Gtk.Container+ContainerChild
            Gtk.Alignment w16 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w17 = new Gtk.HBox();
            w17.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w18 = new Gtk.Image();
            w18.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
            w17.Add(w18);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w20 = new Gtk.Label();
            w20.LabelProp = Mono.Unix.Catalog.GetString("button1");
            w20.UseUnderline = true;
            w17.Add(w20);
            w16.Add(w17);
            this.addTaggerDataConfbutton.Add(w16);
            this.hbox2.Add(this.addTaggerDataConfbutton);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox2[this.addTaggerDataConfbutton]));
            w24.Position = 0;
            w24.Expand = false;
            w24.Fill = false;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w25.PackType = ((Gtk.PackType)(1));
            w25.Position = 1;
            w25.Expand = false;
            w25.Fill = false;
            this.GtkAlignment5.Add(this.vbox1);
            this.frame2.Add(this.GtkAlignment5);
            this.GtkLabel5 = new Gtk.Label();
            this.GtkLabel5.Name = "GtkLabel5";
            this.GtkLabel5.LabelProp = Mono.Unix.Catalog.GetString("<b>data dependant</b>");
            this.GtkLabel5.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel5;
            this.vbox3.Add(this.frame2);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox3[this.frame2]));
            w28.Position = 1;
            this.GtkAlignment.Add(this.vbox3);
            this.frame1.Add(this.GtkAlignment);
            this.frameLabel = new Gtk.Label();
            this.frameLabel.Name = "frameLabel";
            this.frameLabel.LabelProp = Mono.Unix.Catalog.GetString("<b>frame1</b>");
            this.frameLabel.UseMarkup = true;
            this.frame1.LabelWidget = this.frameLabel;
            this.Add(this.frame1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.removeButton.Released += new System.EventHandler(this.OnRemoveButtonReleased);
            this.foregroundCheckButton.Released += new System.EventHandler(this.OnForegroundCheckButtonReleased);
            this.dataCheckButton.Released += new System.EventHandler(this.OnDataCheckButtonReleased);
            this.backgroundCheckButton.Released += new System.EventHandler(this.OnBackgroundCheckButtonReleased);
            this.addTaggerDataConfbutton.Released += new System.EventHandler(this.OnAddTaggerDataConfbuttonReleased);
        }
    }
}
