// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace sermon2 {
    
    
    public partial class MainWindow {
        
        private Gtk.Action HelpAction;
        
        private Gtk.Action AboutAction;
        
        private Gtk.VBox vbox2;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.Notebook notebook1;
        
        private Gtk.HBox hbox2;
        
        private Gtk.HPaned hpaned3;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView configTreeView;
        
        private Gtk.VBox vbox3;
        
        private Gtk.ScrolledWindow scrolledwindow2;
        
        private Gtk.ScrolledWindow commonConfScrolledWindow;
        
        private Gtk.HBox hbox3;
        
        private Gtk.ComboBox objectAddComboBox;
        
        private Gtk.Button NewObjButton;
        
        private Gtk.Label label4;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Button button1;
        
        private Gtk.Button button24;
        
        private Gtk.Statusbar statusbar2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget sermon2.MainWindow
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("Help"), null, null);
            this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
            w2.Add(this.HelpAction, null);
            this.AboutAction = new Gtk.Action("AboutAction", Mono.Unix.Catalog.GetString("About"), null, "gtk-about");
            this.AboutAction.ShortLabel = Mono.Unix.Catalog.GetString("About");
            w2.Add(this.AboutAction, null);
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "sermon2.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("MainWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.BorderWidth = ((uint)(3));
            // Container child sermon2.MainWindow.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='HelpAction'><menuitem action='AboutAction'/></menu></menubar></ui>");
            this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox2.Add(this.menubar1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.menubar1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 0;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.hpaned3 = new Gtk.HPaned();
            this.hpaned3.CanFocus = true;
            this.hpaned3.Name = "hpaned3";
            this.hpaned3.Position = 76;
            // Container child hpaned3.Gtk.Paned+PanedChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.configTreeView = new Gtk.TreeView();
            this.configTreeView.CanFocus = true;
            this.configTreeView.Name = "configTreeView";
            this.configTreeView.HeadersClickable = true;
            this.GtkScrolledWindow.Add(this.configTreeView);
            this.hpaned3.Add(this.GtkScrolledWindow);
            Gtk.Paned.PanedChild w5 = ((Gtk.Paned.PanedChild)(this.hpaned3[this.GtkScrolledWindow]));
            w5.Resize = false;
            // Container child hpaned3.Gtk.Paned+PanedChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.scrolledwindow2 = new Gtk.ScrolledWindow();
            this.scrolledwindow2.CanFocus = true;
            this.scrolledwindow2.Name = "scrolledwindow2";
            this.scrolledwindow2.ShadowType = ((Gtk.ShadowType)(1));
            this.scrolledwindow2.BorderWidth = ((uint)(2));
            this.vbox3.Add(this.scrolledwindow2);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.scrolledwindow2]));
            w6.Position = 0;
            // Container child vbox3.Gtk.Box+BoxChild
            this.commonConfScrolledWindow = new Gtk.ScrolledWindow();
            this.commonConfScrolledWindow.CanFocus = true;
            this.commonConfScrolledWindow.Name = "commonConfScrolledWindow";
            this.commonConfScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            this.commonConfScrolledWindow.BorderWidth = ((uint)(3));
            this.vbox3.Add(this.commonConfScrolledWindow);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox3[this.commonConfScrolledWindow]));
            w7.Position = 1;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.objectAddComboBox = Gtk.ComboBox.NewText();
            this.objectAddComboBox.AppendText(Mono.Unix.Catalog.GetString("serial port"));
            this.objectAddComboBox.AppendText(Mono.Unix.Catalog.GetString("tagger"));
            this.objectAddComboBox.AppendText(Mono.Unix.Catalog.GetString("lop"));
            this.objectAddComboBox.AppendText(Mono.Unix.Catalog.GetString("qport"));
            this.objectAddComboBox.AppendText(Mono.Unix.Catalog.GetString("streamview"));
            this.objectAddComboBox.AppendText(Mono.Unix.Catalog.GetString("lopview"));
            this.objectAddComboBox.Name = "objectAddComboBox";
            this.objectAddComboBox.Active = 0;
            this.hbox3.Add(this.objectAddComboBox);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox3[this.objectAddComboBox]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.NewObjButton = new Gtk.Button();
            this.NewObjButton.CanFocus = true;
            this.NewObjButton.Name = "NewObjButton";
            this.NewObjButton.UseUnderline = true;
            // Container child NewObjButton.Gtk.Container+ContainerChild
            Gtk.Alignment w9 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w10 = new Gtk.HBox();
            w10.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w11 = new Gtk.Image();
            w11.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
            w10.Add(w11);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w13 = new Gtk.Label();
            w13.LabelProp = Mono.Unix.Catalog.GetString("new object");
            w13.UseUnderline = true;
            w10.Add(w13);
            w9.Add(w10);
            this.NewObjButton.Add(w9);
            this.hbox3.Add(this.NewObjButton);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox3[this.NewObjButton]));
            w17.Position = 1;
            w17.Expand = false;
            w17.Fill = false;
            this.vbox3.Add(this.hbox3);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
            w18.Position = 2;
            w18.Expand = false;
            w18.Fill = false;
            this.hpaned3.Add(this.vbox3);
            this.hbox2.Add(this.hpaned3);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox2[this.hpaned3]));
            w20.Position = 0;
            this.notebook1.Add(this.hbox2);
            // Notebook tab
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("objects");
            this.notebook1.SetTabLabel(this.hbox2, this.label4);
            this.label4.ShowAll();
            this.vbox2.Add(this.notebook1);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox2[this.notebook1]));
            w22.Position = 1;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.button1 = new Gtk.Button();
            this.button1.CanFocus = true;
            this.button1.Name = "button1";
            this.button1.UseUnderline = true;
            this.button1.Label = Mono.Unix.Catalog.GetString("button1");
            this.hbox1.Add(this.button1);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.hbox1[this.button1]));
            w23.Position = 0;
            w23.Expand = false;
            w23.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.button24 = new Gtk.Button();
            this.button24.CanFocus = true;
            this.button24.Name = "button24";
            this.button24.UseUnderline = true;
            this.button24.Label = Mono.Unix.Catalog.GetString("button24");
            this.hbox1.Add(this.button24);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox1[this.button24]));
            w24.Position = 1;
            w24.Expand = false;
            w24.Fill = false;
            this.vbox2.Add(this.hbox1);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
            w25.Position = 2;
            w25.Expand = false;
            w25.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.statusbar2 = new Gtk.Statusbar();
            this.statusbar2.Name = "statusbar2";
            this.statusbar2.Spacing = 6;
            this.vbox2.Add(this.statusbar2);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.vbox2[this.statusbar2]));
            w26.Position = 3;
            w26.Expand = false;
            w26.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 392;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.AboutAction.Activated += new System.EventHandler(this.OnAboutActionActivated);
            this.configTreeView.RowActivated += new Gtk.RowActivatedHandler(this.OnConfigTreeViewRowActivated);
            this.NewObjButton.Released += new System.EventHandler(this.OnNewObjButtonReleased);
            this.button1.Released += new System.EventHandler(this.OnButton1Released);
            this.button24.Released += new System.EventHandler(this.OnButton24Released);
        }
    }
}
