// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace sermon2 {
    
    
    public partial class TaggerDataConf {
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.Table table1;
        
        private Gtk.CheckButton backgroundCheckButton;
        
        private Gtk.ColorButton backgroundColorButton;
        
        private Gtk.CheckButton foregroundCheckButton;
        
        private Gtk.ColorButton foregroundColorButton;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label valueLabel;
        
        private Gtk.SpinButton valueSpinButton;
        
        private Gtk.Button remButton;
        
        private Gtk.Label frameLabel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget sermon2.TaggerDataConf
            Stetic.BinContainer.Attach(this);
            this.Name = "sermon2.TaggerDataConf";
            // Container child sermon2.TaggerDataConf.Gtk.Container+ContainerChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(1));
            this.frame1.BorderWidth = ((uint)(3));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(2)), ((uint)(3)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.backgroundCheckButton = new Gtk.CheckButton();
            this.backgroundCheckButton.CanFocus = true;
            this.backgroundCheckButton.Name = "backgroundCheckButton";
            this.backgroundCheckButton.Label = Mono.Unix.Catalog.GetString("background");
            this.backgroundCheckButton.DrawIndicator = true;
            this.backgroundCheckButton.UseUnderline = true;
            this.table1.Add(this.backgroundCheckButton);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.backgroundCheckButton]));
            w1.TopAttach = ((uint)(1));
            w1.BottomAttach = ((uint)(2));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.backgroundColorButton = new Gtk.ColorButton();
            this.backgroundColorButton.CanFocus = true;
            this.backgroundColorButton.Events = ((Gdk.EventMask)(784));
            this.backgroundColorButton.Name = "backgroundColorButton";
            this.backgroundColorButton.Title = Mono.Unix.Catalog.GetString("#000000");
            this.table1.Add(this.backgroundColorButton);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.backgroundColorButton]));
            w2.TopAttach = ((uint)(1));
            w2.BottomAttach = ((uint)(2));
            w2.LeftAttach = ((uint)(2));
            w2.RightAttach = ((uint)(3));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.foregroundCheckButton = new Gtk.CheckButton();
            this.foregroundCheckButton.CanFocus = true;
            this.foregroundCheckButton.Name = "foregroundCheckButton";
            this.foregroundCheckButton.Label = Mono.Unix.Catalog.GetString("foreground");
            this.foregroundCheckButton.DrawIndicator = true;
            this.foregroundCheckButton.UseUnderline = true;
            this.table1.Add(this.foregroundCheckButton);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.foregroundCheckButton]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.foregroundColorButton = new Gtk.ColorButton();
            this.foregroundColorButton.CanFocus = true;
            this.foregroundColorButton.Events = ((Gdk.EventMask)(784));
            this.foregroundColorButton.Name = "foregroundColorButton";
            this.table1.Add(this.foregroundColorButton);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.foregroundColorButton]));
            w4.LeftAttach = ((uint)(2));
            w4.RightAttach = ((uint)(3));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.valueLabel = new Gtk.Label();
            this.valueLabel.Name = "valueLabel";
            this.valueLabel.LabelProp = Mono.Unix.Catalog.GetString("value");
            this.hbox1.Add(this.valueLabel);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.valueLabel]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.valueSpinButton = new Gtk.SpinButton(-1, 255, 1);
            this.valueSpinButton.CanFocus = true;
            this.valueSpinButton.Name = "valueSpinButton";
            this.valueSpinButton.Adjustment.PageIncrement = 10;
            this.valueSpinButton.ClimbRate = 1;
            this.valueSpinButton.Numeric = true;
            this.valueSpinButton.Value = -1;
            this.valueSpinButton.Wrap = true;
            this.hbox1.Add(this.valueSpinButton);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox1[this.valueSpinButton]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            this.table1.Add(this.hbox1);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.hbox1]));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.remButton = new Gtk.Button();
            this.remButton.CanFocus = true;
            this.remButton.Name = "remButton";
            this.remButton.UseUnderline = true;
            // Container child remButton.Gtk.Container+ContainerChild
            Gtk.Alignment w8 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w9 = new Gtk.HBox();
            w9.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w10 = new Gtk.Image();
            w10.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-delete", Gtk.IconSize.Menu, 16);
            w9.Add(w10);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w12 = new Gtk.Label();
            w12.LabelProp = Mono.Unix.Catalog.GetString("remove");
            w12.UseUnderline = true;
            w9.Add(w12);
            w8.Add(w9);
            this.remButton.Add(w8);
            this.table1.Add(this.remButton);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table1[this.remButton]));
            w16.TopAttach = ((uint)(1));
            w16.BottomAttach = ((uint)(2));
            w16.XOptions = ((Gtk.AttachOptions)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment.Add(this.table1);
            this.frame1.Add(this.GtkAlignment);
            this.GtkLabel3 = new Gtk.Label();
            this.GtkLabel3.Name = "GtkLabel3";
            this.GtkLabel3.LabelProp = Mono.Unix.Catalog.GetString("<b>frame1</b>");
            this.GtkLabel3.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel3;
            this.Add(this.frame1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.remButton.Released += new System.EventHandler(this.OnRemButtonReleased);
            this.foregroundCheckButton.Pressed += new System.EventHandler(this.OnForegroundCheckButtonPressed);
            this.foregroundCheckButton.Released += new System.EventHandler(this.OnForegroundCheckButtonReleased);
            this.backgroundCheckButton.Released += new System.EventHandler(this.OnBackgroundCheckButtonReleased);
        }
    }
}
