// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace sermon2 {
    
    
    public partial class hexview {
        
        private Gtk.Alignment alignment5;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Table table1;
        
        private Gtk.TextView addrTV;
        
        private Gtk.TextView asciiTV;
        
        private Gtk.TextView hexTV;
        
        private Gtk.VScrollbar vscrollbar1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget sermon2.hexview
            Stetic.BinContainer.Attach(this);
            this.WidthRequest = 440;
            this.Name = "sermon2.hexview";
            // Container child sermon2.hexview.Gtk.Container+ContainerChild
            this.alignment5 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment5.Name = "alignment5";
            this.alignment5.LeftPadding = ((uint)(5));
            this.alignment5.TopPadding = ((uint)(5));
            this.alignment5.RightPadding = ((uint)(5));
            this.alignment5.BottomPadding = ((uint)(5));
            // Container child alignment5.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.WidthRequest = 300;
            this.hbox1.Name = "hbox1";
            // Container child hbox1.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(1)), ((uint)(4)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.addrTV = new Gtk.TextView();
            this.addrTV.WidthRequest = 56;
            this.addrTV.CanFocus = true;
            this.addrTV.Name = "addrTV";
            this.addrTV.Editable = false;
            this.addrTV.CursorVisible = false;
            this.addrTV.WrapMode = ((Gtk.WrapMode)(2));
            this.table1.Add(this.addrTV);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.addrTV]));
            w1.XOptions = ((Gtk.AttachOptions)(6));
            // Container child table1.Gtk.Table+TableChild
            this.asciiTV = new Gtk.TextView();
            this.asciiTV.CanFocus = true;
            this.asciiTV.Name = "asciiTV";
            this.asciiTV.WrapMode = ((Gtk.WrapMode)(1));
            this.table1.Add(this.asciiTV);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.asciiTV]));
            w2.LeftAttach = ((uint)(3));
            w2.RightAttach = ((uint)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hexTV = new Gtk.TextView();
            this.hexTV.CanFocus = true;
            this.hexTV.Name = "hexTV";
            this.hexTV.WrapMode = ((Gtk.WrapMode)(2));
            this.table1.Add(this.hexTV);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.hexTV]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(3));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            this.hbox1.Add(this.table1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.table1]));
            w4.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vscrollbar1 = new Gtk.VScrollbar(null);
            this.vscrollbar1.Name = "vscrollbar1";
            this.vscrollbar1.Adjustment.Upper = 1000;
            this.vscrollbar1.Adjustment.PageIncrement = 5;
            this.vscrollbar1.Adjustment.PageSize = 10;
            this.vscrollbar1.Adjustment.StepIncrement = 1;
            this.hbox1.Add(this.vscrollbar1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.vscrollbar1]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            this.alignment5.Add(this.hbox1);
            this.Add(this.alignment5);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.SizeAllocated += new Gtk.SizeAllocatedHandler(this.OnSizeAllocated);
            this.addrTV.ScrollAdjustmentsSet += new Gtk.ScrollAdjustmentsSetHandler(this.OnAddrTVScrollAdjustmentsSet);
            this.addrTV.ScrollAdjustmentsSet += new Gtk.ScrollAdjustmentsSetHandler(this.OnAddrTVScrollAdjustmentsSet);
            this.vscrollbar1.MoveSlider += new Gtk.MoveSliderHandler(this.OnVscrollbar1MoveSlider);
            this.vscrollbar1.ChangeValue += new Gtk.ChangeValueHandler(this.OnVscrollbar1ChangeValue);
        }
    }
}
