// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace sermon2 {
    
    
    public partial class lopview {
        
        private Gtk.Action TestAction;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.VBox vbox3;
        
        private Gtk.MenuBar menubar2;
        
        private Gtk.VPaned vpaned3;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView treeview1;
        
        private Gtk.HBox hbox2;
        
        private Gtk.ScrolledWindow GtkScrolledWindow1;
        
        private Gtk.TextView textview1;
        
        private Gtk.ScrolledWindow GtkScrolledWindow2;
        
        private Gtk.TextView textview2;
        
        private Gtk.Statusbar statusbar3;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget sermon2.lopview
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.TestAction = new Gtk.Action("TestAction", Mono.Unix.Catalog.GetString("Test"), null, null);
            this.TestAction.ShortLabel = Mono.Unix.Catalog.GetString("Test");
            w2.Add(this.TestAction, null);
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "sermon2.lopview";
            this.Title = Mono.Unix.Catalog.GetString("lopview");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child sermon2.lopview.Gtk.Container+ContainerChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            // Container child alignment1.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><menubar name='menubar2'><menu action='TestAction'/></menubar></ui>");
            this.menubar2 = ((Gtk.MenuBar)(w1.GetWidget("/menubar2")));
            this.menubar2.Name = "menubar2";
            this.vbox3.Add(this.menubar2);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.menubar2]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.vpaned3 = new Gtk.VPaned();
            this.vpaned3.CanFocus = true;
            this.vpaned3.Name = "vpaned3";
            this.vpaned3.Position = 76;
            // Container child vpaned3.Gtk.Paned+PanedChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.treeview1 = new Gtk.TreeView();
            this.treeview1.CanFocus = true;
            this.treeview1.Name = "treeview1";
            this.treeview1.HeadersClickable = true;
            this.GtkScrolledWindow.Add(this.treeview1);
            this.vpaned3.Add(this.GtkScrolledWindow);
            Gtk.Paned.PanedChild w5 = ((Gtk.Paned.PanedChild)(this.vpaned3[this.GtkScrolledWindow]));
            w5.Resize = false;
            // Container child vpaned3.Gtk.Paned+PanedChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
            this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
            this.textview1 = new Gtk.TextView();
            this.textview1.CanFocus = true;
            this.textview1.Name = "textview1";
            this.GtkScrolledWindow1.Add(this.textview1);
            this.hbox2.Add(this.GtkScrolledWindow1);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow1]));
            w7.Position = 0;
            // Container child hbox2.Gtk.Box+BoxChild
            this.GtkScrolledWindow2 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
            this.GtkScrolledWindow2.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
            this.textview2 = new Gtk.TextView();
            this.textview2.CanFocus = true;
            this.textview2.Name = "textview2";
            this.GtkScrolledWindow2.Add(this.textview2);
            this.hbox2.Add(this.GtkScrolledWindow2);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow2]));
            w9.Position = 1;
            this.vpaned3.Add(this.hbox2);
            this.vbox3.Add(this.vpaned3);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox3[this.vpaned3]));
            w11.Position = 1;
            // Container child vbox3.Gtk.Box+BoxChild
            this.statusbar3 = new Gtk.Statusbar();
            this.statusbar3.Name = "statusbar3";
            this.statusbar3.Spacing = 6;
            this.vbox3.Add(this.statusbar3);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox3[this.statusbar3]));
            w12.Position = 2;
            w12.Expand = false;
            w12.Fill = false;
            this.alignment1.Add(this.vbox3);
            this.Add(this.alignment1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 438;
            this.Show();
        }
    }
}
