// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace saftschubser {
    
    
    public partial class KaufenScreen {
        
        private Gtk.HPaned hpaned1;
        
        private saftschubser.ArtikelChooser artikelChooser;
        
        private Gtk.VBox vbox3;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.NodeView nodeview1;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label label5;
        
        private Gtk.Label label6;
        
        private Gtk.Button kaufenBtn;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget saftschubser.KaufenScreen
            Stetic.BinContainer.Attach(this);
            this.Name = "saftschubser.KaufenScreen";
            // Container child saftschubser.KaufenScreen.Gtk.Container+ContainerChild
            this.hpaned1 = new Gtk.HPaned();
            this.hpaned1.CanFocus = true;
            this.hpaned1.Name = "hpaned1";
            this.hpaned1.Position = 423;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.artikelChooser = new saftschubser.ArtikelChooser();
            this.artikelChooser.Events = ((Gdk.EventMask)(256));
            this.artikelChooser.Name = "artikelChooser";
            this.artikelChooser.Offset = ((uint)(0));
            this.hpaned1.Add(this.artikelChooser);
            Gtk.Paned.PanedChild w1 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.artikelChooser]));
            w1.Resize = false;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            this.vbox3.BorderWidth = ((uint)(45));
            // Container child vbox3.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.nodeview1 = new Gtk.NodeView();
            this.nodeview1.CanFocus = true;
            this.nodeview1.Name = "nodeview1";
            this.nodeview1.HeadersClickable = true;
            this.GtkScrolledWindow.Add(this.nodeview1);
            this.vbox3.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
            w3.Position = 0;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xpad = 9;
            this.label5.Xalign = 1F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("<span size=\"xx-large\"><b>Preis:</b></span>");
            this.label5.UseMarkup = true;
            this.hbox2.Add(this.label5);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.label5]));
            w4.Position = 0;
            // Container child hbox2.Gtk.Box+BoxChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("<span size=\"xx-large\"><b>0,00 €</b></span>");
            this.label6.UseMarkup = true;
            this.hbox2.Add(this.label6);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.label6]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            this.vbox3.Add(this.hbox2);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.kaufenBtn = new Gtk.Button();
            this.kaufenBtn.WidthRequest = 0;
            this.kaufenBtn.HeightRequest = 100;
            this.kaufenBtn.CanFocus = true;
            this.kaufenBtn.Name = "kaufenBtn";
            this.kaufenBtn.UseUnderline = true;
            // Container child kaufenBtn.Gtk.Container+ContainerChild
            Gtk.Alignment w7 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w8 = new Gtk.HBox();
            w8.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w9 = new Gtk.Image();
            w9.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Button, 20);
            w8.Add(w9);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w11 = new Gtk.Label();
            w11.LabelProp = Mono.Unix.Catalog.GetString("Kaufen!");
            w11.UseUnderline = true;
            w8.Add(w11);
            w7.Add(w8);
            this.kaufenBtn.Add(w7);
            this.vbox3.Add(this.kaufenBtn);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox3[this.kaufenBtn]));
            w15.PackType = ((Gtk.PackType)(1));
            w15.Position = 2;
            w15.Expand = false;
            w15.Fill = false;
            w15.Padding = ((uint)(10));
            this.hpaned1.Add(this.vbox3);
            this.Add(this.hpaned1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
