// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace saftschubser {
    
    
    public partial class Kauf {
        
        private Gtk.VBox vbox3;
        
        private Gtk.HBox hbox3;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Button button6;
        
        private Gtk.Button button7;
        
        private Gtk.Button button8;
        
        private Gtk.Button button9;
        
        private Gtk.Button button10;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget saftschubser.Kauf
            Stetic.BinContainer.Attach(this);
            this.Name = "saftschubser.Kauf";
            // Container child saftschubser.Kauf.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.button6 = new Gtk.Button();
            this.button6.CanFocus = true;
            this.button6.Name = "button6";
            this.button6.UseUnderline = true;
            this.button6.Label = Mono.Unix.Catalog.GetString("button6");
            this.vbox2.Add(this.button6);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.button6]));
            w1.Position = 0;
            // Container child vbox2.Gtk.Box+BoxChild
            this.button7 = new Gtk.Button();
            this.button7.CanFocus = true;
            this.button7.Name = "button7";
            this.button7.UseUnderline = true;
            this.button7.Label = Mono.Unix.Catalog.GetString("button7");
            this.vbox2.Add(this.button7);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.button7]));
            w2.Position = 1;
            // Container child vbox2.Gtk.Box+BoxChild
            this.button8 = new Gtk.Button();
            this.button8.CanFocus = true;
            this.button8.Name = "button8";
            this.button8.UseUnderline = true;
            this.button8.Label = Mono.Unix.Catalog.GetString("button8");
            this.vbox2.Add(this.button8);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.button8]));
            w3.Position = 2;
            // Container child vbox2.Gtk.Box+BoxChild
            this.button9 = new Gtk.Button();
            this.button9.CanFocus = true;
            this.button9.Name = "button9";
            this.button9.UseUnderline = true;
            this.button9.Label = Mono.Unix.Catalog.GetString("button9");
            this.vbox2.Add(this.button9);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.button9]));
            w4.Position = 3;
            this.hbox3.Add(this.vbox2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox3[this.vbox2]));
            w5.Position = 1;
            w5.Fill = false;
            this.vbox3.Add(this.hbox3);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
            w6.Position = 0;
            // Container child vbox3.Gtk.Box+BoxChild
            this.button10 = new Gtk.Button();
            this.button10.CanFocus = true;
            this.button10.Name = "button10";
            this.button10.UseUnderline = true;
            this.button10.BorderWidth = ((uint)(18));
            // Container child button10.Gtk.Container+ContainerChild
            Gtk.Alignment w7 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w8 = new Gtk.HBox();
            w8.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w9 = new Gtk.Image();
            w9.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-ok", Gtk.IconSize.Menu, 16);
            w8.Add(w9);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w11 = new Gtk.Label();
            w11.LabelProp = Mono.Unix.Catalog.GetString("Bestätigen");
            w11.UseUnderline = true;
            w8.Add(w11);
            w7.Add(w8);
            this.button10.Add(w7);
            this.vbox3.Add(this.button10);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox3[this.button10]));
            w15.Position = 1;
            w15.Expand = false;
            w15.Fill = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
