// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace saftschubser {
    
    
    public partial class Kauf {
        
        private Gtk.VBox vbox3;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Table table1;
        
        private Gtk.Button button6;
        
        private Gtk.Button button7;
        
        private Gtk.Button button8;
        
        private Gtk.Button button9;
        
        private Gtk.Button button10;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget saftschubser.Kauf
            Stetic.BinContainer.Attach(this);
            this.Name = "saftschubser.Kauf";
            // Container child saftschubser.Kauf.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            this.hbox3.BorderWidth = ((uint)(6));
            // Container child hbox3.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(2)), ((uint)(2)), true);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.button6 = new Gtk.Button();
            this.button6.CanFocus = true;
            this.button6.Name = "button6";
            this.button6.UseUnderline = true;
            // Container child button6.Gtk.Container+ContainerChild
            Gtk.Alignment w1 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w2 = new Gtk.HBox();
            w2.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w3 = new Gtk.Image();
            w3.Pixbuf = Gdk.Pixbuf.LoadFromResource("mate.png");
            w2.Add(w3);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w5 = new Gtk.Label();
            w5.LabelProp = Mono.Unix.Catalog.GetString("Mate");
            w5.UseUnderline = true;
            w2.Add(w5);
            w1.Add(w2);
            this.button6.Add(w1);
            this.table1.Add(this.button6);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.button6]));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.button7 = new Gtk.Button();
            this.button7.CanFocus = true;
            this.button7.Name = "button7";
            this.button7.UseUnderline = true;
            // Container child button7.Gtk.Container+ContainerChild
            Gtk.Alignment w10 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w11 = new Gtk.HBox();
            w11.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w12 = new Gtk.Image();
            w12.Pixbuf = Gdk.Pixbuf.LoadFromResource("kola.png");
            w11.Add(w12);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w14 = new Gtk.Label();
            w14.LabelProp = Mono.Unix.Catalog.GetString("Kola");
            w14.UseUnderline = true;
            w11.Add(w14);
            w10.Add(w11);
            this.button7.Add(w10);
            this.table1.Add(this.button7);
            Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table1[this.button7]));
            w18.TopAttach = ((uint)(1));
            w18.BottomAttach = ((uint)(2));
            w18.XOptions = ((Gtk.AttachOptions)(4));
            w18.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.button8 = new Gtk.Button();
            this.button8.CanFocus = true;
            this.button8.Name = "button8";
            this.button8.UseUnderline = true;
            // Container child button8.Gtk.Container+ContainerChild
            Gtk.Alignment w19 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w20 = new Gtk.HBox();
            w20.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w21 = new Gtk.Image();
            w21.Pixbuf = new Gdk.Pixbuf(System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "./brause.png"));
            w20.Add(w21);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w23 = new Gtk.Label();
            w23.LabelProp = Mono.Unix.Catalog.GetString("Brause");
            w23.UseUnderline = true;
            w20.Add(w23);
            w19.Add(w20);
            this.button8.Add(w19);
            this.table1.Add(this.button8);
            Gtk.Table.TableChild w27 = ((Gtk.Table.TableChild)(this.table1[this.button8]));
            w27.LeftAttach = ((uint)(1));
            w27.RightAttach = ((uint)(2));
            w27.XOptions = ((Gtk.AttachOptions)(4));
            w27.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.button9 = new Gtk.Button();
            this.button9.CanFocus = true;
            this.button9.Name = "button9";
            this.button9.UseUnderline = true;
            // Container child button9.Gtk.Container+ContainerChild
            Gtk.Alignment w28 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w29 = new Gtk.HBox();
            w29.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w30 = new Gtk.Image();
            w30.Pixbuf = new Gdk.Pixbuf(System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "./brause2.png"));
            w29.Add(w30);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w32 = new Gtk.Label();
            w32.LabelProp = Mono.Unix.Catalog.GetString("Brause");
            w32.UseUnderline = true;
            w29.Add(w32);
            w28.Add(w29);
            this.button9.Add(w28);
            this.table1.Add(this.button9);
            Gtk.Table.TableChild w36 = ((Gtk.Table.TableChild)(this.table1[this.button9]));
            w36.TopAttach = ((uint)(1));
            w36.BottomAttach = ((uint)(2));
            w36.LeftAttach = ((uint)(1));
            w36.RightAttach = ((uint)(2));
            w36.XOptions = ((Gtk.AttachOptions)(4));
            w36.YOptions = ((Gtk.AttachOptions)(4));
            this.hbox3.Add(this.table1);
            Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.hbox3[this.table1]));
            w37.Position = 1;
            this.vbox3.Add(this.hbox3);
            Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
            w38.Position = 0;
            // Container child vbox3.Gtk.Box+BoxChild
            this.button10 = new Gtk.Button();
            this.button10.CanFocus = true;
            this.button10.Name = "button10";
            this.button10.UseUnderline = true;
            this.button10.BorderWidth = ((uint)(18));
            // Container child button10.Gtk.Container+ContainerChild
            Gtk.Alignment w39 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w40 = new Gtk.HBox();
            w40.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w41 = new Gtk.Image();
            w41.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-ok", Gtk.IconSize.Menu, 16);
            w40.Add(w41);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w43 = new Gtk.Label();
            w43.LabelProp = Mono.Unix.Catalog.GetString("Bestätigen");
            w43.UseUnderline = true;
            w40.Add(w43);
            w39.Add(w40);
            this.button10.Add(w39);
            this.vbox3.Add(this.button10);
            Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.vbox3[this.button10]));
            w47.Position = 1;
            w47.Expand = false;
            w47.Fill = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
