
OBJ            = borg_hw.o main.o util.o pixel.o program.o

MCU_TARGET    = atmega32
DEFS          = -DF_CPU=16000000

# Fuses, special configured for given MCU
LFUSE = 0xa4
HFUSE = 0xd3

include make/avr_tut.mk
