######################################################################
# Automatically generated by qmake (2.00a) Fr Dez 9 12:39:05 2005
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += display.h mainWindow.h
SOURCES += display.cpp main.cpp mainWindow.cpp
