######################################################################
# Automatically generated by qmake (2.00a) Mon Dec 5 00:39:58 2005
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += display.h
SOURCES += display.cpp main.cpp
