######################################################################
# Automatically generated by qmake (2.00a) Fr Dez 9 19:09:20 2005
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += controllPoint.h display.h mainWindow.h
SOURCES += controllPoint.cpp display.cpp main.cpp mainWindow.cpp
