
OBJ            = main.o util.o pixel.o programm.o borg_can.o scrolltext3.o \
				 font_uni53.o borg_hw.o spi.o can.o snake.o eeprom_reserve.o \
				 persistentCounter.o prng.o matrix.o
CANADDR        = 0x24

include ../../make/avr.mk


