######################################################################
# Automatically generated by qmake (2.00a) Sat Jul 15 13:41:01 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += . new
INCLUDEPATH += . new

# Input
HEADERS += LBorgGLWidget.h \
	   LMainWindow.h 
SOURCES += Borg3DWerkzeug.cpp \
           LBorgGLWidget.cpp \
	   LMainWindow.cpp 
QT      += opengl
