#!/bin/bash

PORTS="1234"
IMAGE="10.1.1.14"
OURNET="10.1.1.0/255.255.255.0"

case $1 in
start)
logger "$0 starting"

iptables -N REDLIPS
iptables -I FORWARD -j REDLIPS

for p in $PORTS
do

iptables -A REDLIPS -i tun+ -s ! $OURNET -p tcp --dport $p -j QUEUE
iptables -A REDLIPS -o tun+ -s $IMAGE -p tcp --sport $p -j QUEUE

done


;;

stop)
logger "$0 stopping"

iptables -D FORWARD -j REDLIPS
iptables -F REDLIPS
iptables -X REDLIPS

;;



default)
echo "$0 start|stop"
;;

*) 
echo "$0 start|stop"
esac
