#!/bin/bash
CHECKMAC='00:12:D2:05:A5:E6'
CHECKNAME='Foobar'
CHECKTIME=30
LOCKCMD='gnome-screensaver-command -a'

# Check if a process with the name bt-lockscreend is already running - the dumb way
if [ $(ps ax | grep bt-lockscreend | grep -v grep | wc -l) ]
then
        echo "Already running!"
	exit 1
else
# run our periodic checks
while (true); do
        CHECK=`hcitool name $CHECKMAC`
        if [ "$CHECK" = "$CHECKNAME" ]; then
                echo "$CHECK" > /dev/null
        else
                #echo "lock"
                $LOCKCMD
        fi
        sleep $CHECKTIME
done;

fi
