#!/bin/bash
CHECKMAC='00:12:C3:19:F4:D0'	# MAC address of the device to check for
CHECKNAME='foo'			# Name of the device to check for
CHECKTIME=30			# Time in seconds to wait between checks
LOCKCMD='gnome-screensaver-command -a'	# command we use to lock our screen

# Check if a process with the name bt-lockscreend is already running - the dumb way
if [ $(ps ax | grep bt-lockscreend | grep -v grep | wc -l) ]
then
        echo "Already running!"
	exit 1
else
# run our periodic checks
while (true); do
        CHECK=`hcitool name $CHECKMAC`
        if [ "$CHECK" = "$CHECKNAME" ]; then
                echo "$CHECK" > /dev/null
        else
                #echo "lock"
                $LOCKCMD
        fi
        sleep $CHECKTIME
done;

fi
